import type { Locale, SiteCopy } from '../types/site'

export const languageOptions: Array<{ code: Locale; label: string; short: string }> = [
  { code: 'zh-CN', label: '简体中文', short: 'CN' },
  { code: 'zh-Hant', label: '繁體中文', short: 'HK' },
  { code: 'en', label: 'English', short: 'EN' },
]

export const siteCopy: Record<Locale, SiteCopy> = {
  'zh-CN': {
    skipMain: '跳过导航，前往主要内容',
    homeLabel: '返回 CLEANER 首页',
    navLabel: '页面导航',
    openMenu: '打开导航菜单',
    closeMenu: '关闭导航菜单',
    languageLabel: '切换语言',
    switchToLight: '切换到浅色主题',
    switchToDark: '切换到深色主题',
    headerCta: '了解产品',
    nav: [
      { href: '#platforms', label: '产品版本' },
      { href: '#capabilities', label: '核心能力' },
      { href: '#workflow', label: '安全流程' },
      { href: '#privacy', label: '隐私边界' },
    ],
    hero: {
      ecosystem: 'GCSA 生态产品',
      eyebrow: 'LOCAL-FIRST SYSTEM CARE',
      title: '清理设备，先看清，再动手。',
      lead: '本地优先的 macOS 清理与系统管理工具。扫描、逐项复核、影响确认、默认可恢复——把空间还给你，把决定权留给你。',
      primaryAction: '查看 macOS 能力',
      secondaryAction: 'Windows 开发进度',
      proof: '不含遥测、账号或文件上传 · 清理操作不会在后台自动执行',
      macStatus: 'macOS 14+ · 产品能力',
      windowsStatus: 'Windows 11 · 开发中',
      visualLabel: 'CLEANER 安全清理流程预览',
      scan: '扫描',
      review: '逐项复核',
      confirm: '确认影响',
      recover: '恢复中心',
      reclaimable: '可释放空间',
      selected: '已选择',
      guarded: '高影响项已保护',
    },
    facts: [
      { value: 'macOS 14+', label: '当前平台', description: '完整版与 App Store Lite 独立边界' },
      { value: '本地优先', label: '数据边界', description: '扫描、历史与设备信息留在当前设备' },
      { value: '默认可恢复', label: '执行策略', description: '普通清理优先移到废纸篓' },
    ],
    platforms: {
      eyebrow: 'PRODUCT EDITIONS',
      title: '不同平台，不混淆能力边界',
      description: 'macOS 提供两种独立版本；Windows 版仍在开发，页面只展示已确认的产品方向。',
      items: [
        {
          platform: 'macOS',
          name: 'GCSA Mac Cleaner',
          status: '完整版',
          statusTone: 'ready',
          description: '面向完整清理、应用管理和系统诊断的独立桌面版本。',
          features: ['垃圾与开发者缓存清理', '应用卸载、重置与残留复核', '重复文件与恢复中心', '系统维护、权限与设备诊断'],
          note: '支持 macOS 14 及更高版本。获取渠道以后续正式发布信息为准。',
        },
        {
          platform: 'macOS',
          name: 'GCSA Cleaner',
          status: 'Lite',
          statusTone: 'limited',
          description: '在 App Store 沙盒边界内，只检查你明确授权的文件夹。',
          features: ['授权目录扫描', '≥ 100 MiB 大文件复核', '重复文件内容校验', '始终移到废纸篓'],
          note: 'Lite 与完整版是独立构建和独立安全边界，不是同一个 App 的功能开关。',
        },
        {
          platform: 'Windows 11',
          name: 'GCSA Cleaner for Windows',
          status: '开发中',
          statusTone: 'building',
          description: '透明、可撤销、本地优先的 Windows 健康维护与深度安全检查工具。',
          features: ['健康与垃圾清理', '注册表、启动和网络诊断', '安全基线与只读深度检查', '历史、隔离与逐项恢复'],
          note: '当前不是可下载的正式产品；具体功能、架构支持和发布时间以最终发布版本为准。',
        },
      ],
    },
    capabilities: {
      eyebrow: 'MACOS CAPABILITIES',
      title: '从空间清理，到系统状态复核',
      description: '每项能力都先展示对象、原因和影响，再由你决定是否执行。',
      items: [
        { tag: 'CLEANUP', title: '垃圾与浏览器清理', description: '扫描用户缓存、日志、临时项目、下载、大文件和支持的浏览器数据；密码、书签、历史与扩展明确排除。', icon: 'trash' },
        { tag: 'DEVELOPER', title: '开发者清理', description: '覆盖 Xcode、node_modules、SwiftPM、CocoaPods、Homebrew 及常见开发与 AI 工具缓存，并说明重建成本。', icon: 'code' },
        { tag: 'APPLICATIONS', title: '应用管理与本机审计', description: '支持卸载、重置和残留复核，并通过本机框架展示签名、Gatekeeper、公证、沙盒与安装来源证据。', icon: 'apps' },
        { tag: 'DUPLICATES', title: '大文件与重复文件', description: '按大小分组并计算内容摘要，支持保留策略与 Finder 复核，每组至少保留一份。', icon: 'files' },
        { tag: 'RECOVERY', title: '恢复中心', description: '查看可恢复事务和条目，支持整次或单项恢复；原位置被占用时不会覆盖现有文件。', icon: 'restore' },
        { tag: 'DIAGNOSTICS', title: '系统维护与只读诊断', description: '覆盖 System Data、登录项、维护任务、隐私权限、设备信息和活动监控，并清楚区分可操作项与只读证据。', icon: 'system' },
      ],
    },
    workflow: {
      eyebrow: 'REVIEW BEFORE ACTION',
      title: '每一次修改，都经过同一条安全路径',
      description: 'CLEANER 不把“扫描到”直接等同于“应该删除”。',
      steps: [
        { number: '01', title: '只读扫描', description: '识别允许范围内的候选项，记录路径、类型、大小、修改时间、归属与扫描原因。' },
        { number: '02', title: '逐项复核', description: '全新扫描默认不选中；个人文件、下载、大文件、iCloud 与站点数据不会进入自动推荐。' },
        { number: '03', title: '影响确认', description: '执行前重新生成计划，展示废纸篓、永久删除和被阻止数量；关键变化会要求重新确认。' },
        { number: '04', title: '执行与恢复', description: '逐项报告结果并保存本地历史；符合条件的废纸篓与备份项目可以恢复。' },
      ],
    },
    safety: {
      eyebrow: 'SAFETY BY DEFAULT',
      title: '证据不足，就停止执行',
      description: '安全边界不是提示语，而是执行路径中的硬约束。',
      points: [
        { title: '最小权限', description: '授权不是进入主应用的前提；缺少权限时，只限制受影响的能力。特权 Helper 仅接受白名单操作。' },
        { title: '身份重新校验', description: '路径越权、符号链接逃逸、扫描后文件身份变化或关联应用仍在运行时，操作会被阻止。' },
        { title: '默认可恢复', description: '普通文件与应用默认移到废纸篓；重复文件和卸载操作不会跟随永久删除设置。' },
        { title: '诚实的诊断', description: '未知来源表示本地证据不足，不等于恶意；活动监控只读，不提供结束进程。' },
      ],
      note: 'CLEANER 不是杀毒软件、EDR、内存清理器或自动系统优化器，也不会绕过 SIP、直接写入 TCC 数据库或自动清空废纸篓。',
    },
    windows: {
      eyebrow: 'WINDOWS 11 · IN DEVELOPMENT',
      title: 'Windows 版正在建立可撤销的维护闭环',
      description: 'Windows Cleaner 以普通权限界面、签名规则、受限提权服务和本地恢复记录为基础，面向 Windows 11 x64 与 ARM64。',
      status: '开发中 · 暂无公开下载',
      features: ['健康、垃圾与隐私清理', '注册表、启动项与系统精简', '网络健康、安全基线与 Defender 协同', '本地历史、隔离区与逐项恢复'],
      boundary: '深度安全检查不会在线自动删除驱动、系统服务或启动链；用户态检查也不能被描述为能够排除内核级 Rootkit。',
    },
    faq: {
      eyebrow: 'CLEAR BOUNDARIES',
      title: '清理之前，先把边界说清楚',
      description: '产品不会用模糊的“一键优化”承诺替代可验证的流程。',
      items: [
        { question: '会自动删除扫描到的文件吗？', answer: '不会。全新扫描完成后选中集合为空，所有真实修改都需要明确选择和二次确认，破坏性操作不会自动重试。' },
        { question: 'Mac Cleaner 会上传文件或扫描报告吗？', answer: '不会。当前产品不含遥测、账号、远程扫描报告或文件上传；扫描、历史和设备信息只在当前 Mac 处理与保存。' },
        { question: '永久删除开启后，所有内容都会直接删除吗？', answer: '不会。卸载 App、重复文件和多种高影响场景会强制使用废纸篓或直接阻止，设置不会覆盖这些安全策略。' },
        { question: 'Windows 版现在可以下载吗？', answer: '不可以。Windows 版仍在开发中，站点展示的是当前已确认方向，不代表已经发布或承诺具体发布日期。' },
      ],
    },
    closing: {
      eyebrow: 'KEEP THE DECISION WITH YOU',
      title: '让清理回到证据、选择和可恢复结果',
      description: '先看清空间去向和执行影响，再决定哪些内容应该离开设备。',
      primary: '查看 macOS 版本',
      secondary: '了解 Windows 进度',
    },
    ecosystem: {
      eyebrow: 'GCSA 安全生态',
      title: '更多安全产品',
      description: '从链上资产、网络隐私到家庭与金融环境，将安全防护延伸到每一次数字操作。',
      officialWebsite: '前往官网',
      moreTitle: '更多安全产品',
      moreDescription: '探索完整的 GCSA 安全生态，查看更多面向个人、企业与基础设施的安全产品。',
      viewAll: '查看全部产品',
      products: [
        { type: '安全加密钱包', name: 'GCSA Wallet', description: '安全的数字资产管理与链上风险识别体验。', href: 'https://wallet.gcsa.org/', theme: 'wallet' },
        { type: '加密网络与隐私保护', name: 'GCSA VPN', description: '通过加密连接保护日常上网与公共网络使用。', href: 'https://gsafevpn.com/', theme: 'vpn' },
        { type: '家庭与金融移动安全', name: 'GCSA Home Guard', description: '面向家庭与金融场景的移动安全体检平台。', href: 'https://homeguard.gcsa.org/', theme: 'homeGuard' },
      ],
    },
    footer: {
      menuLabel: '底栏导航', contactUs: '联系我们', email: '联系邮箱', twitter: '推特', telegram: 'Telegram', home: '首页', products: 'GCSA 生态产品', media: 'GCSA 媒体', updates: 'GCSA 动态', join: '加入联盟', about: '关于联盟', privacy: '隐私政策', terms: '使用条款', support: '技术支持', copyright: '© Global Cybersecurity Alliance. 保留所有权利。',
    },
  },
  'zh-Hant': {
    skipMain: '跳過導覽，前往主要內容',
    homeLabel: '返回 CLEANER 首頁',
    navLabel: '頁面導覽',
    openMenu: '開啟導覽選單',
    closeMenu: '關閉導覽選單',
    languageLabel: '切換語言',
    switchToLight: '切換至淺色主題',
    switchToDark: '切換至深色主題',
    headerCta: '了解產品',
    nav: [
      { href: '#platforms', label: '產品版本' },
      { href: '#capabilities', label: '核心能力' },
      { href: '#workflow', label: '安全流程' },
      { href: '#privacy', label: '私隱邊界' },
    ],
    hero: {
      ecosystem: 'GCSA 生態產品', eyebrow: 'LOCAL-FIRST SYSTEM CARE', title: '清理裝置，先看清，再動手。', lead: '本地優先的 macOS 清理與系統管理工具。掃描、逐項覆核、影響確認、預設可恢復——把空間還給你，把決定權留給你。', primaryAction: '查看 macOS 能力', secondaryAction: 'Windows 開發進度', proof: '不含遙測、帳戶或檔案上傳 · 清理操作不會在背景自動執行', macStatus: 'macOS 14+ · 產品能力', windowsStatus: 'Windows 11 · 開發中', visualLabel: 'CLEANER 安全清理流程預覽', scan: '掃描', review: '逐項覆核', confirm: '確認影響', recover: '恢復中心', reclaimable: '可釋放空間', selected: '已選擇', guarded: '高影響項已保護',
    },
    facts: [
      { value: 'macOS 14+', label: '目前平台', description: '完整版與 App Store Lite 獨立邊界' },
      { value: '本地優先', label: '資料邊界', description: '掃描、歷史與裝置資訊留在目前裝置' },
      { value: '預設可恢復', label: '執行策略', description: '一般清理優先移到垃圾桶' },
    ],
    platforms: {
      eyebrow: 'PRODUCT EDITIONS', title: '不同平台，不混淆能力邊界', description: 'macOS 提供兩種獨立版本；Windows 版仍在開發，頁面只展示已確認的產品方向。',
      items: [
        { platform: 'macOS', name: 'GCSA Mac Cleaner', status: '完整版', statusTone: 'ready', description: '面向完整清理、應用管理和系統診斷的獨立桌面版本。', features: ['垃圾與開發者快取清理', '應用解除安裝、重設與殘留覆核', '重複檔案與恢復中心', '系統維護、權限與裝置診斷'], note: '支援 macOS 14 及更高版本。取得渠道以後續正式發布資訊為準。' },
        { platform: 'macOS', name: 'GCSA Cleaner', status: 'Lite', statusTone: 'limited', description: '在 App Store 沙盒邊界內，只檢查你明確授權的資料夾。', features: ['授權目錄掃描', '≥ 100 MiB 大檔案覆核', '重複檔案內容校驗', '始終移到垃圾桶'], note: 'Lite 與完整版是獨立構建和獨立安全邊界，不是同一個 App 的功能開關。' },
        { platform: 'Windows 11', name: 'GCSA Cleaner for Windows', status: '開發中', statusTone: 'building', description: '透明、可撤銷、本地優先的 Windows 健康維護與深度安全檢查工具。', features: ['健康與垃圾清理', '登錄檔、啟動和網路診斷', '安全基線與唯讀深度檢查', '歷史、隔離與逐項恢復'], note: '目前不是可下載的正式產品；具體功能、架構支援和發布時間以最終發布版本為準。' },
      ],
    },
    capabilities: {
      eyebrow: 'MACOS CAPABILITIES', title: '從空間清理，到系統狀態覆核', description: '每項能力都先展示物件、原因和影響，再由你決定是否執行。',
      items: [
        { tag: 'CLEANUP', title: '垃圾與瀏覽器清理', description: '掃描用戶快取、日誌、臨時項目、下載、大檔案和支援的瀏覽器資料；密碼、書籤、歷史與擴展明確排除。', icon: 'trash' },
        { tag: 'DEVELOPER', title: '開發者清理', description: '覆蓋 Xcode、node_modules、SwiftPM、CocoaPods、Homebrew 及常見開發與 AI 工具快取，並說明重建成本。', icon: 'code' },
        { tag: 'APPLICATIONS', title: '應用管理與本機審計', description: '支援解除安裝、重設和殘留覆核，並展示簽名、Gatekeeper、公證、沙盒與安裝來源證據。', icon: 'apps' },
        { tag: 'DUPLICATES', title: '大檔案與重複檔案', description: '按大小分組並計算內容摘要，支援保留策略與 Finder 覆核，每組至少保留一份。', icon: 'files' },
        { tag: 'RECOVERY', title: '恢復中心', description: '查看可恢復事務和項目，支援整次或單項恢復；原位置被佔用時不會覆蓋現有檔案。', icon: 'restore' },
        { tag: 'DIAGNOSTICS', title: '系統維護與唯讀診斷', description: '覆蓋 System Data、登入項目、維護任務、私隱權限、裝置資訊和活動監控。', icon: 'system' },
      ],
    },
    workflow: {
      eyebrow: 'REVIEW BEFORE ACTION', title: '每一次修改，都經過同一條安全路徑', description: 'CLEANER 不把「掃描到」直接等同於「應該刪除」。',
      steps: [
        { number: '01', title: '唯讀掃描', description: '識別允許範圍內的候選項，記錄路徑、類型、大小、修改時間、歸屬與掃描原因。' },
        { number: '02', title: '逐項覆核', description: '全新掃描預設不選中；個人檔案、下載、大檔案、iCloud 與網站資料不會進入自動推薦。' },
        { number: '03', title: '影響確認', description: '執行前重新生成計畫，展示垃圾桶、永久刪除和被阻止數量；關鍵變化會要求重新確認。' },
        { number: '04', title: '執行與恢復', description: '逐項報告結果並儲存本地歷史；符合條件的垃圾桶與備份項目可以恢復。' },
      ],
    },
    safety: {
      eyebrow: 'SAFETY BY DEFAULT', title: '證據不足，就停止執行', description: '安全邊界不是提示語，而是執行路徑中的硬約束。',
      points: [
        { title: '最小權限', description: '授權不是進入主應用的前提；缺少權限時，只限制受影響的能力。特權 Helper 僅接受白名單操作。' },
        { title: '身份重新校驗', description: '路徑越權、符號連結逃逸、掃描後檔案身份變化或關聯應用仍在運行時，操作會被阻止。' },
        { title: '預設可恢復', description: '一般檔案與應用預設移到垃圾桶；重複檔案和解除安裝不會跟隨永久刪除設定。' },
        { title: '誠實的診斷', description: '未知來源表示本地證據不足，不等於惡意；活動監控唯讀，不提供結束程序。' },
      ],
      note: 'CLEANER 不是防毒軟件、EDR、記憶體清理器或自動系統優化器，也不會繞過 SIP、直接寫入 TCC 資料庫或自動清空垃圾桶。',
    },
    windows: {
      eyebrow: 'WINDOWS 11 · IN DEVELOPMENT', title: 'Windows 版正在建立可撤銷的維護閉環', description: 'Windows Cleaner 以一般權限介面、簽名規則、受限提權服務和本地恢復記錄為基礎，面向 Windows 11 x64 與 ARM64。', status: '開發中 · 暫無公開下載', features: ['健康、垃圾與私隱清理', '登錄檔、啟動項目與系統精簡', '網路健康、安全基線與 Defender 協同', '本地歷史、隔離區與逐項恢復'], boundary: '深度安全檢查不會在線自動刪除驅動程式、系統服務或啟動鏈；用戶態檢查也不能被描述為能夠排除內核級 Rootkit。',
    },
    faq: {
      eyebrow: 'CLEAR BOUNDARIES', title: '清理之前，先把邊界說清楚', description: '產品不會用模糊的「一鍵優化」承諾取代可驗證的流程。',
      items: [
        { question: '會自動刪除掃描到的檔案嗎？', answer: '不會。全新掃描完成後選中集合為空，所有真實修改都需要明確選擇和二次確認，破壞性操作不會自動重試。' },
        { question: 'Mac Cleaner 會上傳檔案或掃描報告嗎？', answer: '不會。目前產品不含遙測、帳戶、遠程掃描報告或檔案上傳；掃描、歷史和裝置資訊只在目前 Mac 處理與保存。' },
        { question: '永久刪除開啟後，所有內容都會直接刪除嗎？', answer: '不會。解除安裝 App、重複檔案和多種高影響場景會強制使用垃圾桶或直接阻止，設定不會覆蓋這些安全策略。' },
        { question: 'Windows 版現在可以下載嗎？', answer: '不可以。Windows 版仍在開發中，網站展示的是目前已確認方向，不代表已經發布或承諾具體日期。' },
      ],
    },
    closing: { eyebrow: 'KEEP THE DECISION WITH YOU', title: '讓清理回到證據、選擇和可恢復結果', description: '先看清空間去向和執行影響，再決定哪些內容應該離開裝置。', primary: '查看 macOS 版本', secondary: '了解 Windows 進度' },
    ecosystem: {
      eyebrow: 'GCSA 安全生態', title: '更多安全產品', description: '從鏈上資產、網路私隱到家庭與金融環境，將安全防護延伸到每一次數碼操作。', officialWebsite: '前往官網', moreTitle: '更多安全產品', moreDescription: '探索完整的 GCSA 安全生態，查看更多面向個人、企業與基礎設施的安全產品。', viewAll: '查看全部產品',
      products: [
        { type: '安全加密錢包', name: 'GCSA Wallet', description: '安全的數碼資產管理與鏈上風險識別體驗。', href: 'https://wallet.gcsa.org/', theme: 'wallet' },
        { type: '加密網路與私隱保護', name: 'GCSA VPN', description: '透過加密連線保護日常上網與公共網路使用。', href: 'https://gsafevpn.com/', theme: 'vpn' },
        { type: '家庭與金融移動安全', name: 'GCSA Home Guard', description: '面向家庭與金融場景的移動安全體檢平台。', href: 'https://homeguard.gcsa.org/', theme: 'homeGuard' },
      ],
    },
    footer: { menuLabel: '頁尾導覽', contactUs: '聯繫我們', email: '聯繫郵箱', twitter: '推特', telegram: 'Telegram', home: '首頁', products: 'GCSA 生態產品', media: 'GCSA 媒體', updates: 'GCSA 動態', join: '加入聯盟', about: '關於聯盟', privacy: '隱私政策', terms: '使用條款', support: '技術支持', copyright: '© Global Cybersecurity Alliance. 保留所有權利。' },
  },
  en: {
    skipMain: 'Skip navigation and go to main content', homeLabel: 'Back to the CLEANER home page', navLabel: 'Page navigation', openMenu: 'Open navigation menu', closeMenu: 'Close navigation menu', languageLabel: 'Switch language', switchToLight: 'Switch to light theme', switchToDark: 'Switch to dark theme', headerCta: 'Explore',
    nav: [
      { href: '#platforms', label: 'Editions' },
      { href: '#capabilities', label: 'Capabilities' },
      { href: '#workflow', label: 'Safety flow' },
      { href: '#privacy', label: 'Privacy' },
    ],
    hero: { ecosystem: 'A GCSA ecosystem product', eyebrow: 'LOCAL-FIRST SYSTEM CARE', title: 'See clearly before you clean.', lead: 'A local-first macOS cleanup and system-management tool. Scan, review each item, confirm the impact, and recover by default—reclaim space without giving up control.', primaryAction: 'Explore macOS capabilities', secondaryAction: 'Windows progress', proof: 'No telemetry, account, or file uploads · Cleanup never runs silently in the background', macStatus: 'macOS 14+ · Product capabilities', windowsStatus: 'Windows 11 · In development', visualLabel: 'CLEANER safety workflow preview', scan: 'Scan', review: 'Review', confirm: 'Confirm', recover: 'Recovery', reclaimable: 'Reclaimable', selected: 'Selected', guarded: 'High-impact items guarded' },
    facts: [
      { value: 'macOS 14+', label: 'Current platform', description: 'Full and App Store Lite have separate boundaries' },
      { value: 'Local first', label: 'Data boundary', description: 'Scans, history, and device data stay on device' },
      { value: 'Recoverable by default', label: 'Execution policy', description: 'Ordinary cleanup prefers the Trash' },
    ],
    platforms: {
      eyebrow: 'PRODUCT EDITIONS', title: 'Clear boundaries for every platform', description: 'macOS has two independent editions. Windows remains in development, so this page shows direction—not release claims.',
      items: [
        { platform: 'macOS', name: 'GCSA Mac Cleaner', status: 'Full edition', statusTone: 'ready', description: 'A standalone desktop edition for complete cleanup, application management, and system diagnostics.', features: ['Junk and developer-cache cleanup', 'App uninstall, reset, and residue review', 'Duplicate files and recovery center', 'Maintenance, permissions, and device diagnostics'], note: 'Supports macOS 14 and later. Distribution details will be provided with the formal release.' },
        { platform: 'macOS', name: 'GCSA Cleaner', status: 'Lite', statusTone: 'limited', description: 'Works strictly within the App Store sandbox and folders you explicitly authorize.', features: ['Authorized-folder scans', 'Review files ≥ 100 MiB', 'Content-verified duplicate groups', 'Always moves items to the Trash'], note: 'Lite and Full are separate builds with separate security boundaries—not one app with disabled switches.' },
        { platform: 'Windows 11', name: 'GCSA Cleaner for Windows', status: 'In development', statusTone: 'building', description: 'A transparent, reversible, local-first Windows maintenance and deep-security inspection tool.', features: ['Health and junk cleanup', 'Registry, startup, and network diagnostics', 'Security baseline and read-only deep checks', 'History, quarantine, and item-level recovery'], note: 'This is not currently a downloadable product. Features, architecture support, and timing remain subject to the final release.' },
      ],
    },
    capabilities: {
      eyebrow: 'MACOS CAPABILITIES', title: 'From reclaiming space to reviewing system state', description: 'Every capability presents the object, evidence, and impact before you choose an action.',
      items: [
        { tag: 'CLEANUP', title: 'Junk and browser cleanup', description: 'Review user caches, logs, temporary items, downloads, large files, and supported browser data. Passwords, bookmarks, history, and extensions are excluded.', icon: 'trash' },
        { tag: 'DEVELOPER', title: 'Developer cleanup', description: 'Covers Xcode, node_modules, SwiftPM, CocoaPods, Homebrew, and common development or AI-tool caches with rebuild-cost context.', icon: 'code' },
        { tag: 'APPLICATIONS', title: 'App management and local audit', description: 'Uninstall, reset, or review residue while inspecting local signing, Gatekeeper, notarization, sandbox, and installation evidence.', icon: 'apps' },
        { tag: 'DUPLICATES', title: 'Large and duplicate files', description: 'Group by size, verify content hashes, choose a keep policy, and review in Finder. Every group retains at least one file.', icon: 'files' },
        { tag: 'RECOVERY', title: 'Recovery center', description: 'Review recoverable transactions and restore a batch or one item. Existing files are never overwritten during recovery.', icon: 'restore' },
        { tag: 'DIAGNOSTICS', title: 'Maintenance and read-only diagnostics', description: 'Review System Data, background items, maintenance tasks, privacy permissions, device details, and activity without pretending every finding is actionable.', icon: 'system' },
      ],
    },
    workflow: {
      eyebrow: 'REVIEW BEFORE ACTION', title: 'Every modification follows one safety path', description: 'CLEANER never treats “found” as meaning “should be deleted.”',
      steps: [
        { number: '01', title: 'Read-only scan', description: 'Identify candidates inside allowed scopes and record path, type, size, time, ownership, and scan reason.' },
        { number: '02', title: 'Item-by-item review', description: 'A new scan selects nothing. Personal files, Downloads, large files, iCloud data, and site data never enter automatic recommendations.' },
        { number: '03', title: 'Impact confirmation', description: 'Regenerate the plan before execution and show Trash, permanent-delete, and blocked counts. Material changes require another review.' },
        { number: '04', title: 'Execute and recover', description: 'Report per-item outcomes and keep local history. Eligible Trash and backed-up items can be restored.' },
      ],
    },
    safety: {
      eyebrow: 'SAFETY BY DEFAULT', title: 'When evidence is insufficient, execution stops', description: 'Safety boundaries are enforced in the execution path—not left as warning copy.',
      points: [
        { title: 'Least privilege', description: 'Permissions are not required to enter the app. Missing access limits only affected capabilities, and the privileged helper accepts only allowlisted operations.' },
        { title: 'Identity revalidation', description: 'Path escape, symlink escape, post-scan identity changes, or a related running app block execution.' },
        { title: 'Recoverable by default', description: 'Ordinary files and apps prefer the Trash. Duplicate cleanup and app uninstall do not inherit a permanent-delete preference.' },
        { title: 'Honest diagnostics', description: 'Unknown provenance means local evidence is insufficient—not malicious. Activity Monitor is read-only and cannot terminate processes.' },
      ],
      note: 'CLEANER is not antivirus, EDR, a memory cleaner, or an automatic optimizer. It does not bypass SIP, write directly to TCC, or empty the Trash automatically.',
    },
    windows: { eyebrow: 'WINDOWS 11 · IN DEVELOPMENT', title: 'Building a reversible maintenance loop for Windows', description: 'Windows Cleaner combines a standard-privilege UI, signed rules, a restricted elevation broker, and local recovery records for Windows 11 x64 and ARM64.', status: 'In development · No public download', features: ['Health, junk, and privacy cleanup', 'Registry, startup, and system debloat review', 'Network health, security baseline, and Defender coordination', 'Local history, quarantine, and item-level recovery'], boundary: 'Deep security checks will not automatically delete drivers, system services, or boot-chain objects on a live system. User-mode checks also cannot rule out a kernel-level rootkit.' },
    faq: {
      eyebrow: 'CLEAR BOUNDARIES', title: 'Set the boundaries before cleanup begins', description: 'The product does not replace evidence with a vague “one-click optimization” promise.',
      items: [
        { question: 'Does CLEANER automatically delete scan results?', answer: 'No. A fresh scan selects nothing. Every real modification requires an explicit selection and confirmation, and destructive actions never retry automatically.' },
        { question: 'Does Mac Cleaner upload files or reports?', answer: 'No. The current product has no telemetry, account, remote scan report, or file upload. Scans, history, and device information remain on the Mac.' },
        { question: 'Does enabling permanent deletion apply everywhere?', answer: 'No. App uninstall, duplicate files, and multiple high-impact contexts force the Trash or block the operation. Preferences cannot override those safeguards.' },
        { question: 'Can I download the Windows edition now?', answer: 'No. It remains in development. The site describes confirmed direction, not a published product or a promised release date.' },
      ],
    },
    closing: { eyebrow: 'KEEP THE DECISION WITH YOU', title: 'Bring cleanup back to evidence, choice, and recoverable results', description: 'Understand where space went and what an action changes before deciding what should leave the device.', primary: 'Explore macOS editions', secondary: 'View Windows progress' },
    ecosystem: {
      eyebrow: 'GCSA Security Ecosystem', title: 'More security products', description: 'Extend protection from on-chain assets and online privacy to home and financial environments.', officialWebsite: 'Official website', moreTitle: 'More security products', moreDescription: 'Explore the complete GCSA security ecosystem for individuals, businesses, and infrastructure.', viewAll: 'View all products',
      products: [
        { type: 'Secure crypto wallet', name: 'GCSA Wallet', description: 'Secure digital-asset management with on-chain risk insight.', href: 'https://wallet.gcsa.org/', theme: 'wallet' },
        { type: 'Encrypted network and privacy', name: 'GCSA VPN', description: 'Encrypted connections for everyday browsing and public networks.', href: 'https://gsafevpn.com/', theme: 'vpn' },
        { type: 'Home and financial mobile security', name: 'GCSA Home Guard', description: 'Mobile security checkups for home and financial scenarios.', href: 'https://homeguard.gcsa.org/', theme: 'homeGuard' },
      ],
    },
    footer: { menuLabel: 'Footer navigation', contactUs: 'Contact Us', email: 'Email', twitter: 'Twitter', telegram: 'Telegram', home: 'Home', products: 'GCSA Ecosystem Products', media: 'GCSA Media', updates: 'GCSA Updates', join: 'Join the Alliance', about: 'About Alliance', privacy: 'Privacy Policy', terms: 'Terms of Use', support: 'Technical Support', copyright: '© Global Cybersecurity Alliance. All rights reserved.' },
  },
}
