import type { Locale } from '../types/site'
import type { LegalLocaleCopy } from '../types/legal'

export const legalCopy: Record<Locale, LegalLocaleCopy> = {
  'zh-CN': {
    sectionNavLabel: '本页目录',
    pages: {
      privacy: {
        eyebrow: 'PRIVACY POLICY',
        title: '隐私政策',
        summary: '本政策说明水印分析 iOS 与 Android 应用及相关公开页面如何处理、保存、传输和保护数据，以及用户如何管理相关数据。',
        dateLabel: '最后更新',
        date: '2026 年 8 月 3 日',
        sections: [
          {
            id: 'overview',
            title: '1. 隐私原则',
            paragraphs: ['水印分析（WATERMARK）由 Global Cybersecurity Alliance Limited（GCSA）提供。产品采用本地处理设计：检测和智能打码所需的媒体内容在用户设备上处理。'],
            bullets: ['不要求注册或登录账号。', '不通过广告追踪用户。', '不为远程检测或分析上传图片、视频或音频原文件。', '不在后台扫描整个照片库或持续读取剪贴板。'],
          },
          {
            id: 'processing',
            title: '2. 应用处理的数据',
            paragraphs: ['当用户主动选择媒体进行检测或智能打码时，应用可能在设备本地读取和生成以下数据，以完成用户请求的功能。'],
            bullets: ['用户选择的图片、视频或音频及其文件表示。', '文件名、类型、MIME、大小、SHA-256、EXIF、XMP、内容凭证和容器信息。', '检测器输出、证据、警告、未执行原因、缩略图及检测报告。', '智能打码所需的人脸或敏感文字候选、OCR 文本、编辑区域、样式和导出副本。'],
          },
          {
            id: 'storage',
            title: '3. 本地保存',
            paragraphs: ['为支持历史记录和继续编辑，应用可在自身受保护的本地目录中保存检测报告、缩略图、受管媒体副本、智能打码项目和编辑状态。这些内容不会同步或上传到 GCSA 服务器。', '用户照片库或“文件”中的原始媒体仍由用户和操作系统管理；删除水印分析内的记录不会删除这些外部原文件。'],
          },
          {
            id: 'collection',
            title: '4. 数据收集与共享',
            paragraphs: ['当前移动应用不要求账号，也不包含广告。用户选择的媒体、检测报告、OCR 文本和检测中间结果不会发送给 Firebase，也不会作为使用分析或诊断内容。应用会按照下一节发送有限的稳定性、性能诊断和应用使用分析。', '如果用户主动通过电子邮件联系我们，邮件地址、邮件内容和用户选择附加的材料会发送给 GCSA，并由相关邮件服务提供商处理。请不要发送与问题无关的敏感媒体或个人信息。'],
          },
          {
            id: 'diagnostics',
            title: '5. Firebase 诊断与使用分析',
            paragraphs: ['iOS 与 Android 版本使用 Google Firebase Crashlytics 和 Firebase Performance Monitoring 处理应用稳定性与性能诊断。诊断可能包括崩溃堆栈及相关应用状态、安装与会话标识符、设备型号、操作系统、应用版本、CPU、内存、磁盘、网络类型、启动与前后台时长、页面渲染及网络请求性能，以及用于国家或地区归类的 IP 地址。', '新安装默认开启 Firebase Analytics、Crashlytics 和 Performance。用户可在应用“设置 → 隐私与权限”关闭统一开关以撤回同意；选择会跨启动保留。关闭后会停止未来的 Analytics 和 Performance 数据发送，并删除待发送的 Crashlytics 报告；Crashlytics 自动收集状态在下次启动时完全生效。重新开启表示同意恢复这些匿名诊断与使用分析。', 'iOS 与 Android 版本还包含 Google Analytics for Firebase。Analytics 会自动处理应用实例标识符、首次打开、应用启动、会话与互动等默认事件，以及设备、应用和粗略地区信息。应用不设置账号 User ID，也不显示广告；Android 明确关闭 Advertising ID，iOS 使用不含广告身份支持的 Analytics Core 并关闭 IDFV 与广告个性化信号。GCSA 将这些信息用于汇总了解产品使用情况和改进应用，不用于数据经纪、广告或跨应用追踪。', '这些 Firebase 数据会传送给 Google/Firebase。应用不会把用户选择的媒体、缩略图、EXIF/XMP、GPS、OCR 原文、检测报告、检测器证据、频域或 embedding 特征、检测中间结果或编辑区域附加到 Firebase 事件。Firebase 可能在 Google 或其服务提供商运营设施的地区处理数据，并按照其适用条款和隐私政策处理服务数据。', '按照 Firebase 当前公开的保留说明，Crashlytics 的崩溃堆栈和相关标识符保留 90 天后开始删除；Performance Monitoring 的 IP 关联事件保留 30 天，安装关联和去标识化性能数据保留 60 天后开始删除。Google Analytics 的用户级和事件级数据按照项目配置保留，标准属性最长为 14 个月；汇总报告不一定受相同保留控制。'],
            links: [
              { label: 'Firebase iOS 数据披露说明', href: 'https://firebase.google.com/docs/ios/app-store-data-collection' },
              { label: 'Firebase Android 数据披露说明', href: 'https://firebase.google.com/docs/android/play-data-disclosure' },
              { label: 'Google Analytics 数据收集说明', href: 'https://support.google.com/analytics/answer/11593727' },
              { label: 'Firebase 隐私与保留说明', href: 'https://firebase.google.com/support/privacy' },
            ],
          },
          {
            id: 'website',
            title: '6. 官网与公开页面',
            paragraphs: ['访问 watermarkinspector.gcsa.org 时，Cloudflare 和本站源服务器会为交付页面、防止滥用、维护安全和排查故障处理标准网络信息，例如 IP 地址、请求时间、请求 URL、浏览器或设备 User-Agent、来源页面以及网络和安全事件。服务器日志仅在安全、运维或适用法律所需的期限内保留。本站不使用这些信息建立广告画像。', '本站从 Google Fonts 加载网页字体。浏览器会因此直接请求 Google 的服务器，Google 会按照其自身隐私政策处理相应的网络和设备信息。用户主动打开其他外部链接时，相应服务也会按照其自身条款和隐私政策处理数据。'],
            links: [
              { label: 'Cloudflare 隐私政策', href: 'https://www.cloudflare.com/privacypolicy/' },
              { label: 'Google 隐私政策', href: 'https://policies.google.com/privacy' },
            ],
          },
          {
            id: 'permissions',
            title: '7. 系统权限与用户选择',
            paragraphs: ['应用仅在功能需要时调用照片、文件、相机或剪贴板等系统能力。媒体导入由用户主动发起，并受 iOS、Android 及系统选择器提供的授权范围控制。拒绝可选权限可能限制相应功能，但不会授权应用在后台扩大访问范围。', 'Firebase 遥测不依赖照片、相机或完整媒体库权限。用户可在应用内统一开启或关闭 Firebase 遥测；关闭遥测不会影响本地导入、检测、报告或智能打码。'],
          },
          {
            id: 'deletion',
            title: '8. 保留、删除与隐私选择',
            paragraphs: ['本地记录会保留到用户在应用中删除、清除应用数据或卸载应用。删除检测或打码记录时，应用会尝试一并删除其管理的报告、缩略图、工作副本和相关元数据；删除本地记录不会删除 Firebase 已接收的数据。', '水印分析不提供用户账号。Firebase 数据与假名化的应用安装或实例标识符关联，而不是与支持邮箱账号关联，因此 GCSA 通常无法仅凭电子邮件定位某一条 Firebase 记录；已接收的数据按上一节的自动保留周期和适用的 Firebase 删除机制处理。用户可在应用设置中关闭遥测以阻止未来发送，并删除设备上待发送的崩溃报告。清除应用数据或卸载会停止当前安装后续收集并重置本地实例状态，但重新安装后会按新安装默认开启并可能创建新的应用实例。用户可通过 contact@gcsa.org 请求处理支持通信和其他可合理定位的数据，或咨询访问、删除、限制和反对处理等隐私选择；法律、安全或必要业务记录可能需要在适用期限内保留。'],
          },
          {
            id: 'external',
            title: '9. 外部链接与商店服务',
            paragraphs: ['用户主动打开 GCSA 官网、应用商店、X、Telegram 或邮件入口时，会离开水印分析的本地媒体处理环境。相应服务根据其自身条款和隐私政策处理数据。Apple 与 Google 也会分别处理应用下载、商店评价、平台诊断或设备相关信息；应用主动启用的 Firebase 诊断则按照本政策第 5 节处理。'],
          },
          {
            id: 'security',
            title: '10. 安全与能力边界',
            paragraphs: ['应用使用操作系统沙箱和平台安全能力保护本地数据，但任何存储或软件系统都无法保证绝对安全。建议用户使用设备锁、系统更新和可信备份。', '“未发现当前已支持的水印”只表示已完成的支持项未识别到相应信号，不代表媒体一定没有水印，也不构成真实性保证。'],
          },
          {
            id: 'children',
            title: '11. 儿童隐私',
            paragraphs: ['水印分析不是专门面向儿童设计的服务，也不会有意要求儿童提交个人信息。如果监护人认为儿童通过支持渠道提供了个人信息，请联系我们处理。'],
          },
          {
            id: 'changes',
            title: '12. 政策更新',
            paragraphs: ['当产品功能、数据处理方式或适用要求发生变化时，我们可能更新本政策，并在本页标注新的生效日期。重大变化会通过适当方式提供说明。'],
          },
        ],
        contactTitle: '隐私问题',
        contactDescription: '如需咨询本政策、本地数据管理或支持通信中的个人信息，请联系 GCSA。',
        contactAction: '联系 contact@gcsa.org',
      },
      terms: {
        eyebrow: 'TERMS OF USE',
        title: '使用条款',
        summary: '这些条款规定用户使用水印分析 iOS 与 Android 应用及相关公开页面时的权利、责任和产品边界。',
        dateLabel: '最后更新',
        date: '2026 年 8 月 1 日',
        sections: [
          {
            id: 'acceptance',
            title: '1. 接受条款',
            paragraphs: ['本条款由 Global Cybersecurity Alliance Limited（GCSA）提供并适用于水印分析。下载、安装或使用水印分析，即表示用户同意本条款和隐私政策。如果用户不同意，请不要使用本应用。应用商店的附加规则也可能适用于下载、更新和付款相关事项。'],
          },
          {
            id: 'service',
            title: '2. 产品用途',
            paragraphs: ['水印分析是本地媒体检查与隐私打码工具，用于检查当前版本支持的内容凭证、水印信号、元数据和可疑特征，并帮助用户遮挡图片中的人脸或敏感信息。', '水印分析不提供移除水印、破坏内容凭证、绕过平台检测或证明媒体绝对真实的功能。'],
          },
          {
            id: 'license',
            title: '3. 使用许可',
            paragraphs: ['在用户遵守本条款的前提下，GCSA 授予用户一项有限、非独占、不可转让、可撤销的许可，仅用于在用户拥有或控制的兼容设备上进行个人或合法组织用途。应用及其品牌、设计、代码和文档的权利仍归相应权利人所有。'],
          },
          {
            id: 'content',
            title: '4. 用户内容与责任',
            paragraphs: ['用户保留对其媒体和导出结果依法享有的权利。用户应确保有权导入、分析、编辑和分享相关内容，并对使用检测结果作出的决定负责。', '应用不会取得用户媒体的所有权。本地处理不改变用户对原始内容的法律责任。'],
          },
          {
            id: 'prohibited',
            title: '5. 禁止行为',
            paragraphs: ['用户不得利用水印分析从事违法、侵权、欺诈或危害他人的活动。'],
            bullets: ['不得尝试利用应用移除水印、破坏内容凭证或规避检测。', '不得反编译、攻击、干扰或滥用应用及相关服务，但适用法律明确允许的除外。', '不得上传、分析或分享无权处理的内容。', '不得把检测结果冒充为法律鉴定、来源认证或绝对真实性证明。'],
          },
          {
            id: 'results',
            title: '6. 检测结果与限制',
            paragraphs: ['检测结果取决于媒体格式、压缩、转码、裁剪、检测器、模型、运行时和当前支持范围。未知或封闭水印、损坏文件以及未执行的检查可能影响结论。', '“已检测到”“疑似检测到”“未发现”或“未支持”等状态应结合报告中的证据、警告和限制理解。用户不应仅依赖水印分析作出法律、财务、安全或其他高风险决定。'],
          },
          {
            id: 'privacy',
            title: '7. 隐私与本地数据',
            paragraphs: ['应用的数据处理受水印分析隐私政策约束。用户负责管理设备访问权限、本地历史记录、导出文件和系统分享目标。'],
          },
          {
            id: 'availability',
            title: '8. 更新与可用性',
            paragraphs: ['GCSA 可以为安全、兼容性、政策或功能原因更新、修改、暂停或停止部分能力。不同平台、设备、系统版本和地区的功能可能不同。我们不保证所有检测器、格式或第三方能力始终可用。'],
          },
          {
            id: 'third-party',
            title: '9. 第三方服务',
            paragraphs: ['应用商店、操作系统、外部网站、社交平台和邮件服务由第三方提供，并受其自身条款约束。GCSA 不控制第三方服务的可用性或数据处理。'],
          },
          {
            id: 'disclaimer',
            title: '10. 免责声明与责任限制',
            paragraphs: ['在适用法律允许的最大范围内，水印分析按“现状”和“可用”状态提供，不作检测完整性、适销性、特定用途适用性或不侵权的默示保证。', '在适用法律允许的最大范围内，GCSA 不对因使用或无法使用应用、依赖检测结果、数据丢失或第三方服务产生的间接、附带、特殊或后果性损失承担责任。法律不允许排除的权利不受本条款影响。'],
          },
          {
            id: 'changes',
            title: '11. 条款变更',
            paragraphs: ['我们可能更新本条款，并在本页标注新的生效日期。继续使用更新后的应用表示用户接受届时适用的条款；如不同意，应停止使用并卸载应用。'],
          },
        ],
        contactTitle: '条款咨询',
        contactDescription: '如对使用许可、产品边界或本条款有疑问，请联系 GCSA。',
        contactAction: '联系 contact@gcsa.org',
      },
      support: {
        eyebrow: 'TECHNICAL SUPPORT',
        title: '技术支持',
        summary: '获取 iOS 与 Android 版本的使用说明、结果解释、隐私数据管理和故障排查帮助。',
        dateLabel: '最后更新',
        date: '2026 年 8 月 1 日',
        sections: [
          {
            id: 'start',
            title: '1. 快速开始',
            paragraphs: ['水印分析无需注册或登录。打开应用后，可从照片、系统文件入口或剪贴板选择媒体，并在设备本地开始检查。'],
            bullets: ['选择用户有权处理的图片、视频或音频。', '等待应用规划并完成当前设备支持的检测项目。', '查看总体结论，再展开证据、警告、未执行项和能力限制。', '需要分享图片时，可进入智能打码复核并导出新的 PNG 副本。'],
          },
          {
            id: 'import',
            title: '2. 无法导入或读取媒体',
            paragraphs: ['请确认文件未损坏、设备有足够可用空间，并已向系统选择器授予本次访问。实际可读取格式取决于操作系统解码能力和当前检测器支持。', '如果系统照片或文件入口没有显示目标内容，请先在对应系统应用中确认文件可正常打开，再重新选择。'],
          },
          {
            id: 'results',
            title: '3. 如何理解检测结果',
            paragraphs: ['“未发现当前已支持的水印”不等于媒体一定没有水印。“疑似检测到”需要人工复核；“未执行”或“不支持”表示当前格式、模型、profile、签名材料或运行条件不足。', '请在报告中同时查看检测器状态、证据、警告和采样范围，不要只依据单一状态标签判断媒体真实性。'],
          },
          {
            id: 'redaction',
            title: '4. 智能打码',
            paragraphs: ['智能打码会在本地建议人脸和敏感文字区域。自动结果可能漏检或误检，导出前应逐项复核、移动、缩放、新增或删除区域。', '导出会创建新的 PNG 副本，不覆盖原图，并移除原图元数据。智能打码不是水印移除工具。'],
          },
          {
            id: 'history',
            title: '5. 历史记录与本地数据',
            paragraphs: ['检测报告、缩略图、受管副本和打码项目保存在应用本地目录。用户可在应用内删除记录；清除应用数据或卸载应用也会移除应用容器中的本地内容。', '删除应用内记录不会删除照片库或“文件”中的原始媒体。'],
          },
          {
            id: 'troubleshooting',
            title: '6. 常见故障排查',
            bullets: ['将水印分析更新到应用商店提供的最新版本。', '确认 iOS 或 Android 已更新到受支持版本。', '关闭并重新打开应用，再重试同一媒体。', '确认设备存储空间充足，并检查系统授予的照片或文件访问范围。', '如问题仅出现在单个文件，请记录文件类型、大小和错误提示；不要直接发送敏感原文件。'],
            paragraphs: [],
          },
          {
            id: 'contact',
            title: '7. 联系技术支持',
            paragraphs: ['发送邮件时，请提供设备型号、系统版本、水印分析版本、问题发生步骤和可见错误信息。除非确有必要且用户愿意，请不要附加包含个人信息的媒体、检测报告或打码原图。', '水印分析不需要测试账号，也不提供订阅或应用内购买恢复流程。'],
          },
        ],
        contactTitle: '需要进一步帮助？',
        contactDescription: '通过电子邮件联系 GCSA 技术支持。请勿在邮件中发送与问题无关的敏感媒体。',
        contactAction: '发送邮件至 contact@gcsa.org',
      },
    },
  },
  'zh-Hant': {
    sectionNavLabel: '本頁目錄',
    pages: {
      privacy: {
        eyebrow: 'PRIVACY POLICY',
        title: '私隱政策',
        summary: '本政策說明水印分析 iOS 與 Android 應用及相關公開頁面如何處理、保存、傳輸和保護資料，以及用戶如何管理相關資料。',
        dateLabel: '最後更新',
        date: '2026 年 8 月 3 日',
        sections: [
          { id: 'overview', title: '1. 私隱原則', paragraphs: ['水印分析（WATERMARK）由 Global Cybersecurity Alliance Limited（GCSA）提供。產品採用本地處理設計：檢測和智能打碼所需的媒體內容在用戶裝置上處理。'], bullets: ['不要求註冊或登入帳戶。', '不透過廣告追蹤用戶。', '不為遠端檢測或分析上傳圖片、影片或音訊原檔。', '不在背景掃描整個相片庫或持續讀取剪貼簿。'] },
          { id: 'processing', title: '2. 應用處理的資料', paragraphs: ['當用戶主動選擇媒體進行檢測或智能打碼時，應用可能在裝置本地讀取和產生以下資料，以完成用戶要求的功能。'], bullets: ['用戶選擇的圖片、影片或音訊及其檔案表示。', '檔案名稱、類型、MIME、大小、SHA-256、EXIF、XMP、內容憑證和容器資訊。', '檢測器輸出、證據、警告、未執行原因、縮圖及檢測報告。', '智能打碼所需的人臉或敏感文字候選、OCR 文字、編輯區域、樣式和匯出副本。'] },
          { id: 'storage', title: '3. 本地保存', paragraphs: ['為支援歷史記錄和繼續編輯，應用可在自身受保護的本地目錄中保存檢測報告、縮圖、受管媒體副本、智能打碼項目和編輯狀態。這些內容不會同步或上傳到 GCSA 伺服器。', '用戶相片庫或「檔案」中的原始媒體仍由用戶和作業系統管理；刪除水印分析內的記錄不會刪除這些外部原檔。'] },
          { id: 'collection', title: '4. 資料收集與分享', paragraphs: ['目前移動應用不要求帳戶，也不包含廣告。用戶選擇的媒體、檢測報告、OCR 文字和檢測中間結果不會傳送給 Firebase，也不會作為使用分析或診斷內容。應用會按照下一節傳送有限的穩定性、效能診斷和應用使用分析。', '如果用戶主動透過電郵聯絡我們，電郵地址、郵件內容和用戶選擇附加的材料會傳送給 GCSA，並由相關郵件服務供應商處理。請勿傳送與問題無關的敏感媒體或個人資料。'] },
          { id: 'diagnostics', title: '5. Firebase 診斷與使用分析', paragraphs: ['iOS 與 Android 版本使用 Google Firebase Crashlytics 和 Firebase Performance Monitoring 處理應用穩定性與效能診斷。診斷可能包括崩潰堆疊及相關應用狀態、安裝與工作階段識別碼、裝置型號、作業系統、應用版本、CPU、記憶體、磁碟、網絡類型、啟動與前後台時長、畫面渲染及網絡請求效能，以及用於國家或地區分類的 IP 位址。', '新安裝預設開啟 Firebase Analytics、Crashlytics 和 Performance。用戶可在應用「設定 → 私隱與權限」關閉統一開關以撤回同意；選擇會跨啟動保留。關閉後會停止未來的 Analytics 和 Performance 資料傳送，並刪除待傳送的 Crashlytics 報告；Crashlytics 自動收集狀態在下次啟動時完全生效。重新開啟表示同意恢復這些匿名診斷與使用分析。', 'iOS 與 Android 版本亦包含 Google Analytics for Firebase。Analytics 會自動處理應用實例識別碼、首次開啟、應用啟動、工作階段與互動等預設事件，以及裝置、應用和概略地區資訊。應用不設定帳戶 User ID，也不顯示廣告；Android 明確關閉 Advertising ID，iOS 使用不含廣告身分支援的 Analytics Core 並關閉 IDFV 與廣告個人化訊號。GCSA 將這些資訊用於匯總了解產品使用情況和改善應用，不用於資料經紀、廣告或跨應用追蹤。', '這些 Firebase 資料會傳送給 Google/Firebase。應用不會把用戶選擇的媒體、縮圖、EXIF/XMP、GPS、OCR 原文、檢測報告、檢測器證據、頻域或 embedding 特徵、檢測中間結果或編輯區域附加到 Firebase 事件。Firebase 可能在 Google 或其服務供應商營運設施的地區處理資料，並按照其適用條款和私隱政策處理服務資料。', '按照 Firebase 目前公開的保留說明，Crashlytics 的崩潰堆疊和相關識別碼保留 90 天後開始刪除；Performance Monitoring 的 IP 關聯事件保留 30 天，安裝關聯和去識別化效能資料保留 60 天後開始刪除。Google Analytics 的用戶層級和事件層級資料按照項目設定保留，標準屬性最長為 14 個月；匯總報告不一定受相同保留控制。'], links: [{ label: 'Firebase iOS 資料披露說明', href: 'https://firebase.google.com/docs/ios/app-store-data-collection' }, { label: 'Firebase Android 資料披露說明', href: 'https://firebase.google.com/docs/android/play-data-disclosure' }, { label: 'Google Analytics 資料收集說明', href: 'https://support.google.com/analytics/answer/11593727' }, { label: 'Firebase 私隱與保留說明', href: 'https://firebase.google.com/support/privacy' }] },
          { id: 'website', title: '6. 官網與公開頁面', paragraphs: ['瀏覽 watermarkinspector.gcsa.org 時，Cloudflare 和本站來源伺服器會為交付頁面、防止濫用、維護安全和故障排除處理標準網絡資訊，例如 IP 位址、請求時間、請求 URL、瀏覽器或裝置 User-Agent、來源頁面以及網絡和安全事件。伺服器日誌只會在安全、營運或適用法律所需的期限內保留。本站不使用這些資訊建立廣告檔案。', '本站從 Google Fonts 載入網頁字型。瀏覽器會因此直接請求 Google 的伺服器，Google 會按照其自身私隱政策處理相應的網絡和裝置資訊。用戶主動開啟其他外部連結時，相應服務亦會按照其自身條款和私隱政策處理資料。'], links: [{ label: 'Cloudflare 私隱政策', href: 'https://www.cloudflare.com/privacypolicy/' }, { label: 'Google 私隱政策', href: 'https://policies.google.com/privacy' }] },
          { id: 'permissions', title: '7. 系統權限與用戶選擇', paragraphs: ['應用僅在功能需要時調用相片、檔案、相機或剪貼簿等系統能力。媒體匯入由用戶主動發起，並受 iOS、Android 及系統選擇器提供的授權範圍控制。拒絕可選權限可能限制相應功能，但不會授權應用在背景擴大存取範圍。', 'Firebase 遙測不依賴相片、相機或完整媒體庫權限。用戶可在應用內統一開啟或關閉 Firebase 遙測；關閉遙測不會影響本機匯入、檢測、報告或智能打碼。'] },
          { id: 'deletion', title: '8. 保留、刪除與私隱選擇', paragraphs: ['本地記錄會保留到用戶在應用中刪除、清除應用資料或解除安裝應用。刪除檢測或打碼記錄時，應用會嘗試一併刪除其管理的報告、縮圖、工作副本和相關中繼資料；刪除本地記錄不會刪除 Firebase 已接收的資料。', '水印分析不提供用戶帳戶。Firebase 資料與假名化的應用安裝或實例識別碼關聯，而非與支援電郵帳戶關聯，因此 GCSA 通常無法僅憑電郵定位某一筆 Firebase 記錄；已接收的資料按上一節的自動保留週期和適用的 Firebase 刪除機制處理。用戶可在應用設定中關閉遙測以阻止未來傳送，並刪除裝置上待傳送的崩潰報告。清除應用資料或解除安裝會停止目前安裝後續收集並重設本地實例狀態，但重新安裝後會按新安裝預設開啟並可能建立新的應用實例。用戶可透過 contact@gcsa.org 要求處理支援通信和其他可合理定位的資料，或查詢存取、刪除、限制和反對處理等私隱選擇；法律、安全或必要業務記錄可能需要在適用期限內保留。'] },
          { id: 'external', title: '9. 外部連結與商店服務', paragraphs: ['用戶主動開啟 GCSA 官網、應用商店、X、Telegram 或電郵入口時，會離開水印分析的本地媒體處理環境。相應服務根據其自身條款和私隱政策處理資料。Apple 與 Google 亦會分別處理應用下載、商店評價、平台診斷或裝置相關資訊；應用主動啟用的 Firebase 診斷則按照本政策第 5 節處理。'] },
          { id: 'security', title: '10. 安全與能力邊界', paragraphs: ['應用使用作業系統沙箱和平台安全能力保護本地資料，但任何儲存或軟件系統都無法保證絕對安全。建議用戶使用裝置鎖、系統更新和可信備份。', '「未發現目前已支援的浮水印」只表示已完成的支援項未識別到相應訊號，不代表媒體一定沒有浮水印，也不構成真實性保證。'] },
          { id: 'children', title: '11. 兒童私隱', paragraphs: ['水印分析並非專門面向兒童設計的服務，也不會有意要求兒童提交個人資料。如果監護人認為兒童透過支援渠道提供了個人資料，請聯絡我們處理。'] },
          { id: 'changes', title: '12. 政策更新', paragraphs: ['當產品功能、資料處理方式或適用要求發生變化時，我們可能更新本政策，並在本頁標示新的生效日期。重大變化會透過適當方式提供說明。'] },
        ],
        contactTitle: '私隱問題',
        contactDescription: '如需查詢本政策、本地資料管理或支援通信中的個人資料，請聯絡 GCSA。',
        contactAction: '聯絡 contact@gcsa.org',
      },
      terms: {
        eyebrow: 'TERMS OF USE',
        title: '使用條款',
        summary: '這些條款規定用戶使用水印分析 iOS 與 Android 應用及相關公開頁面時的權利、責任和產品邊界。',
        dateLabel: '最後更新',
        date: '2026 年 8 月 1 日',
        sections: [
          { id: 'acceptance', title: '1. 接受條款', paragraphs: ['本條款由 Global Cybersecurity Alliance Limited（GCSA）提供並適用於水印分析。下載、安裝或使用水印分析，即表示用戶同意本條款和私隱政策。如果用戶不同意，請勿使用本應用。應用商店的附加規則也可能適用於下載、更新和付款相關事項。'] },
          { id: 'service', title: '2. 產品用途', paragraphs: ['水印分析是本地媒體檢查與私隱打碼工具，用於檢查目前版本支援的內容憑證、浮水印訊號、中繼資料和可疑特徵，並協助用戶遮擋圖片中的人臉或敏感資訊。', '水印分析不提供移除浮水印、破壞內容憑證、繞過平台檢測或證明媒體絕對真實的功能。'] },
          { id: 'license', title: '3. 使用許可', paragraphs: ['在用戶遵守本條款的前提下，GCSA 授予用戶一項有限、非獨佔、不可轉讓、可撤銷的許可，僅用於在用戶擁有或控制的相容裝置上進行個人或合法組織用途。應用及其品牌、設計、程式碼和文件的權利仍歸相應權利人所有。'] },
          { id: 'content', title: '4. 用戶內容與責任', paragraphs: ['用戶保留對其媒體和匯出結果依法享有的權利。用戶應確保有權匯入、分析、編輯和分享相關內容，並對使用檢測結果作出的決定負責。', '應用不會取得用戶媒體的所有權。本地處理不改變用戶對原始內容的法律責任。'] },
          { id: 'prohibited', title: '5. 禁止行為', paragraphs: ['用戶不得利用水印分析從事違法、侵權、欺詐或危害他人的活動。'], bullets: ['不得嘗試利用應用移除浮水印、破壞內容憑證或規避檢測。', '不得反編譯、攻擊、干擾或濫用應用及相關服務，但適用法律明確允許的除外。', '不得上傳、分析或分享無權處理的內容。', '不得把檢測結果冒充為法律鑑定、來源認證或絕對真實性證明。'] },
          { id: 'results', title: '6. 檢測結果與限制', paragraphs: ['檢測結果取決於媒體格式、壓縮、轉碼、裁剪、檢測器、模型、執行環境和目前支援範圍。未知或封閉浮水印、損壞檔案以及未執行的檢查可能影響結論。', '「已檢測到」「疑似檢測到」「未發現」或「不支援」等狀態應結合報告中的證據、警告和限制理解。用戶不應僅依賴水印分析作出法律、財務、安全或其他高風險決定。'] },
          { id: 'privacy', title: '7. 私隱與本地資料', paragraphs: ['應用的資料處理受水印分析私隱政策約束。用戶負責管理裝置存取權限、本地歷史記錄、匯出檔案和系統分享目標。'] },
          { id: 'availability', title: '8. 更新與可用性', paragraphs: ['GCSA 可以為安全、相容性、政策或功能原因更新、修改、暫停或停止部分能力。不同平台、裝置、系統版本和地區的功能可能不同。我們不保證所有檢測器、格式或第三方能力始終可用。'] },
          { id: 'third-party', title: '9. 第三方服務', paragraphs: ['應用商店、作業系統、外部網站、社交平台和郵件服務由第三方提供，並受其自身條款約束。GCSA 不控制第三方服務的可用性或資料處理。'] },
          { id: 'disclaimer', title: '10. 免責聲明與責任限制', paragraphs: ['在適用法律允許的最大範圍內，水印分析按「現狀」和「可用」狀態提供，不作檢測完整性、適銷性、特定用途適用性或不侵權的默示保證。', '在適用法律允許的最大範圍內，GCSA 不對因使用或無法使用應用、依賴檢測結果、資料遺失或第三方服務產生的間接、附帶、特殊或後果性損失承擔責任。法律不允許排除的權利不受本條款影響。'] },
          { id: 'changes', title: '11. 條款變更', paragraphs: ['我們可能更新本條款，並在本頁標示新的生效日期。繼續使用更新後的應用表示用戶接受屆時適用的條款；如不同意，應停止使用並解除安裝應用。'] },
        ],
        contactTitle: '條款查詢',
        contactDescription: '如對使用許可、產品邊界或本條款有疑問，請聯絡 GCSA。',
        contactAction: '聯絡 contact@gcsa.org',
      },
      support: {
        eyebrow: 'TECHNICAL SUPPORT',
        title: '技術支援',
        summary: '取得 iOS 與 Android 版本的使用說明、結果解釋、私隱資料管理和故障排除協助。',
        dateLabel: '最後更新',
        date: '2026 年 8 月 1 日',
        sections: [
          { id: 'start', title: '1. 快速開始', paragraphs: ['水印分析無需註冊或登入。開啟應用後，可從相片、系統檔案入口或剪貼簿選擇媒體，並在裝置本地開始檢查。'], bullets: ['選擇用戶有權處理的圖片、影片或音訊。', '等待應用規劃並完成目前裝置支援的檢測項目。', '查看總體結論，再展開證據、警告、未執行項和能力限制。', '需要分享圖片時，可進入智能打碼覆核並匯出新的 PNG 副本。'] },
          { id: 'import', title: '2. 無法匯入或讀取媒體', paragraphs: ['請確認檔案未損壞、裝置有足夠可用空間，並已向系統選擇器授予本次存取。實際可讀取格式取決於作業系統解碼能力和目前檢測器支援。', '如果系統相片或檔案入口沒有顯示目標內容，請先在對應系統應用中確認檔案可正常開啟，再重新選擇。'] },
          { id: 'results', title: '3. 如何理解檢測結果', paragraphs: ['「未發現目前已支援的浮水印」不等於媒體一定沒有浮水印。「疑似檢測到」需要人工覆核；「未執行」或「不支援」表示目前格式、模型、profile、簽名材料或執行條件不足。', '請在報告中同時查看檢測器狀態、證據、警告和採樣範圍，不要只依據單一狀態標籤判斷媒體真實性。'] },
          { id: 'redaction', title: '4. 智能打碼', paragraphs: ['智能打碼會在本地建議人臉和敏感文字區域。自動結果可能漏檢或誤檢，匯出前應逐項覆核、移動、縮放、新增或刪除區域。', '匯出會建立新的 PNG 副本，不覆蓋原圖，並移除原圖中繼資料。智能打碼不是浮水印移除工具。'] },
          { id: 'history', title: '5. 歷史記錄與本地資料', paragraphs: ['檢測報告、縮圖、受管副本和打碼項目保存在應用本地目錄。用戶可在應用內刪除記錄；清除應用資料或解除安裝應用也會移除應用容器中的本地內容。', '刪除應用內記錄不會刪除相片庫或「檔案」中的原始媒體。'] },
          { id: 'troubleshooting', title: '6. 常見故障排除', paragraphs: [], bullets: ['將水印分析更新到應用商店提供的最新版本。', '確認 iOS 或 Android 已更新到受支援版本。', '關閉並重新開啟應用，再重試同一媒體。', '確認裝置儲存空間充足，並檢查系統授予的相片或檔案存取範圍。', '如問題僅出現在單個檔案，請記錄檔案類型、大小和錯誤提示；不要直接傳送敏感原檔。'] },
          { id: 'contact', title: '7. 聯絡技術支援', paragraphs: ['傳送郵件時，請提供裝置型號、系統版本、水印分析版本、問題發生步驟和可見錯誤資訊。除非確有必要且用戶願意，請勿附加包含個人資料的媒體、檢測報告或打碼原圖。', '水印分析不需要測試帳戶，也不提供訂閱或應用程式內購買恢復流程。'] },
        ],
        contactTitle: '需要進一步協助？',
        contactDescription: '透過電郵聯絡 GCSA 技術支援。請勿在郵件中傳送與問題無關的敏感媒體。',
        contactAction: '傳送郵件至 contact@gcsa.org',
      },
    },
  },
  en: {
    sectionNavLabel: 'On this page',
    pages: {
      privacy: {
        eyebrow: 'PRIVACY POLICY',
        title: 'Privacy Policy',
        summary: 'This policy explains how the WATERMARK iOS and Android apps and related public pages process, retain, transmit, and protect data, and how users can manage related data.',
        dateLabel: 'Last updated',
        date: 'August 3, 2026',
        sections: [
          { id: 'overview', title: '1. Privacy principles', paragraphs: ['WATERMARK (Watermark Inspector) is provided by Global Cybersecurity Alliance Limited (GCSA). Media required for inspection and Smart Redaction is processed on the user’s device.'], bullets: ['No account or sign-in is required.', 'The app does not track users through advertising.', 'Original images, video, and audio are not uploaded for remote inspection or analysis.', 'The app does not silently scan the entire photo library or continuously monitor the clipboard.'] },
          { id: 'processing', title: '2. Data processed by the app', paragraphs: ['When a user selects media for inspection or Smart Redaction, the app may read and create the following data locally to perform the requested feature.'], bullets: ['Images, video, or audio selected by the user and their file representations.', 'File name, type, MIME, size, SHA-256, EXIF, XMP, content credentials, and container information.', 'Detector output, evidence, warnings, skipped-check reasons, thumbnails, and inspection reports.', 'Face or sensitive-text candidates, OCR text, edit regions, styles, and exported copies used by Smart Redaction.'] },
          { id: 'storage', title: '3. Local storage', paragraphs: ['To provide history and resume editing, the app may store inspection reports, thumbnails, managed media copies, Smart Redaction projects, and edit state in its protected local directory. This content is not synced or uploaded to GCSA servers.', 'Original media in Photos or Files remains under the control of the user and operating system. Deleting a WATERMARK record does not delete those external originals.'] },
          { id: 'collection', title: '4. Collection and sharing', paragraphs: ['The current mobile apps do not require an account or contain advertising. User-selected media, inspection reports, OCR text, and detector intermediates are not sent to Firebase or used as analytics or diagnostic content. The apps send limited stability and performance diagnostics and app-usage analytics as described below.', 'If a user contacts us by email, the email address, message, and any material the user chooses to attach are sent to GCSA and processed by the relevant email providers. Do not send unrelated sensitive media or personal information.'] },
          { id: 'diagnostics', title: '5. Firebase diagnostics and usage analytics', paragraphs: ['The iOS and Android apps use Google Firebase Crashlytics and Firebase Performance Monitoring for stability and performance diagnostics. Diagnostic data can include crash stacks and relevant application state; installation and session identifiers; device model; operating system; app version; CPU, memory, disk, and network information; app start, foreground, background, screen-rendering, and network-request performance; and IP addresses used for country or region mapping.', 'Firebase Analytics, Crashlytics, and Performance are enabled by default on new installs. A user can withdraw consent through the single switch under Settings → Privacy & Permissions; the choice persists across launches. Turning it off stops future Analytics and Performance uploads and deletes pending Crashlytics reports. The Crashlytics automatic-collection setting fully applies on the next launch. Turning the switch on again means consenting to resume these anonymous diagnostics and usage analytics.', 'The iOS and Android apps also include Google Analytics for Firebase. Analytics automatically processes an app-instance identifier, default events such as first open, app start, sessions, and engagement, and device, app, and approximate-region information. The app does not set an account User ID or display ads. Android explicitly disables Advertising ID collection; iOS uses Analytics Core without advertising identity support and disables IDFV and ad-personalization signals. GCSA uses this information to understand aggregate product usage and improve the app, not for data brokerage, advertising, or cross-app tracking.', 'This Firebase data is transmitted to Google/Firebase. The app does not attach selected media, thumbnails, EXIF/XMP, GPS, raw OCR text, inspection reports, detector evidence, frequency-domain or embedding features, detector intermediates, or edit regions to Firebase events. Firebase may process data in regions where Google or its service providers operate facilities and processes service data under its applicable terms and privacy policy.', 'Under Firebase’s current published retention information, Crashlytics crash stacks and associated identifiers are kept for 90 days before deletion begins. Performance Monitoring keeps IP-associated events for 30 days and installation-associated and de-identified performance data for 60 days before deletion begins. Google Analytics user-level and event-level data is retained according to the project setting, up to 14 months for a standard property; aggregate reports are not necessarily governed by the same retention control.'], links: [{ label: 'Firebase iOS App Store data disclosure', href: 'https://firebase.google.com/docs/ios/app-store-data-collection' }, { label: 'Firebase Android Play data disclosure', href: 'https://firebase.google.com/docs/android/play-data-disclosure' }, { label: 'Google Analytics data collection', href: 'https://support.google.com/analytics/answer/11593727' }, { label: 'Firebase privacy and retention', href: 'https://firebase.google.com/support/privacy' }] },
          { id: 'website', title: '6. Website and public pages', paragraphs: ['When a visitor opens watermarkinspector.gcsa.org, Cloudflare and the site’s origin server process standard network information to deliver pages, prevent abuse, maintain security, and troubleshoot errors. This can include IP address, request time, requested URL, browser or device User-Agent, referrer, and network or security events. Server logs are retained only as needed for security, operations, or applicable law. The site does not use this information to create advertising profiles.', 'The site loads web fonts from Google Fonts. The visitor’s browser therefore makes direct requests to Google, which processes the related network and device information under its own privacy policy. Other external links opened by the user are also governed by the relevant service’s terms and privacy policy.'], links: [{ label: 'Cloudflare Privacy Policy', href: 'https://www.cloudflare.com/privacypolicy/' }, { label: 'Google Privacy Policy', href: 'https://policies.google.com/privacy' }] },
          { id: 'permissions', title: '7. Device permissions and user choice', paragraphs: ['The app invokes system capabilities such as Photos, Files, camera, or clipboard only when needed for a feature. Media import is initiated by the user and limited by the authorization provided through iOS, Android, and their system pickers. Declining an optional permission may limit the related feature but does not grant broader background access.', 'Firebase telemetry does not rely on Photos, camera, or full-library permission. Users can control all three Firebase products with one in-app switch. Turning telemetry off does not affect local import, inspection, reports, or Smart Redaction.'] },
          { id: 'deletion', title: '8. Retention, deletion, and privacy choices', paragraphs: ['Local records remain until the user deletes them in the app, clears app data, or uninstalls the app. When an inspection or redaction record is deleted, the app attempts to remove its managed report, thumbnail, working copy, and related metadata. Deleting a local record does not delete data already received by Firebase.', 'WATERMARK does not offer user accounts. Firebase data is associated with pseudonymous app-installation or app-instance identifiers rather than a support-email account, so GCSA generally cannot locate an individual Firebase record from an email address alone. Received data is handled under the automatic retention periods above and applicable Firebase deletion mechanisms. Users can turn telemetry off in app settings to stop future uploads and delete pending crash reports on the device. Clearing app data or uninstalling stops collection for the current installation and resets local instance state; a reinstall is a new install, defaults telemetry on, and can create a new app instance. Users may contact contact@gcsa.org to request action on support communications and other reasonably locatable data, or to ask about access, deletion, restriction, and objection choices. Legal, security, or necessary business records may need to be retained for an applicable period.'] },
          { id: 'external', title: '9. External links and store services', paragraphs: ['When a user opens the GCSA website, an app store, X, Telegram, or email, they leave WATERMARK’s local media-processing environment. Those services process data under their own terms and privacy policies. Apple and Google separately handle app downloads, store reviews, platform diagnostics, or device-related information; Firebase diagnostics enabled by the app are handled under section 5 of this policy.'] },
          { id: 'security', title: '10. Security and capability limits', paragraphs: ['The app uses operating-system sandboxing and platform security capabilities to protect local data, but no storage or software system can guarantee absolute security. Users should keep device locks and system updates enabled and maintain trusted backups.', '“No supported watermark found” only means completed supported checks did not identify the relevant signal. It does not prove that no watermark exists or guarantee authenticity.'] },
          { id: 'children', title: '11. Children’s privacy', paragraphs: ['WATERMARK is not directed specifically to children and does not intentionally ask children to submit personal information. A guardian who believes a child provided personal information through a support channel may contact us.'] },
          { id: 'changes', title: '12. Policy updates', paragraphs: ['We may update this policy when product functionality, data practices, or applicable requirements change. The updated effective date will appear on this page, and material changes will be described through an appropriate channel.'] },
        ],
        contactTitle: 'Privacy questions',
        contactDescription: 'Contact GCSA with questions about this policy, local data management, or personal information in support communications.',
        contactAction: 'Email contact@gcsa.org',
      },
      terms: {
        eyebrow: 'TERMS OF USE',
        title: 'Terms of Use',
        summary: 'These terms define the rights, responsibilities, and product boundaries that apply to the WATERMARK iOS and Android apps and related public pages.',
        dateLabel: 'Last updated',
        date: 'August 1, 2026',
        sections: [
          { id: 'acceptance', title: '1. Acceptance', paragraphs: ['These Terms are provided by Global Cybersecurity Alliance Limited (GCSA) and apply to WATERMARK. By downloading, installing, or using WATERMARK, the user agrees to these Terms and the Privacy Policy. If the user does not agree, they should not use the app. Additional app-store rules may apply to downloads, updates, and payment-related matters.'] },
          { id: 'service', title: '2. Product purpose', paragraphs: ['WATERMARK is a local media-inspection and privacy-redaction tool. It inspects supported content credentials, watermark signals, metadata, and suspicious characteristics and helps users mask faces or sensitive information in images.', 'WATERMARK does not remove watermarks, damage content credentials, evade platform detection, or prove that media is absolutely authentic.'] },
          { id: 'license', title: '3. License', paragraphs: ['Subject to these Terms, GCSA grants the user a limited, non-exclusive, non-transferable, revocable license to use the app for personal or lawful organizational purposes on compatible devices the user owns or controls. Rights in the app, brand, design, code, and documentation remain with their respective owners.'] },
          { id: 'content', title: '4. User content and responsibility', paragraphs: ['Users retain their lawful rights in media and exported results. They must have the right to import, inspect, edit, and share the relevant content and are responsible for decisions made using inspection results.', 'The app does not claim ownership of user media. Local processing does not change the user’s legal responsibility for the original content.'] },
          { id: 'prohibited', title: '5. Prohibited conduct', paragraphs: ['Users may not use WATERMARK for unlawful, infringing, fraudulent, or harmful activity.'], bullets: ['Do not attempt to use the app to remove watermarks, damage content credentials, or evade detection.', 'Do not reverse engineer, attack, interfere with, or misuse the app or related services except where applicable law expressly permits it.', 'Do not import, inspect, or share content that you have no right to process.', 'Do not present an inspection result as a legal examination, source certification, or absolute proof of authenticity.'] },
          { id: 'results', title: '6. Inspection results and limits', paragraphs: ['Results depend on media format, compression, transcoding, cropping, detectors, models, runtime conditions, and current support. Unknown or closed watermark systems, damaged files, and skipped checks can affect a conclusion.', 'Statuses such as “detected,” “suspected,” “not found,” and “unsupported” must be read together with the evidence, warnings, and limits in the report. Users should not rely solely on WATERMARK for legal, financial, security, or other high-risk decisions.'] },
          { id: 'privacy', title: '7. Privacy and local data', paragraphs: ['Data handling in the app is governed by the WATERMARK Privacy Policy. Users are responsible for managing device permissions, local history, exported files, and system share destinations.'] },
          { id: 'availability', title: '8. Updates and availability', paragraphs: ['GCSA may update, modify, suspend, or discontinue capabilities for security, compatibility, policy, or product reasons. Features can vary by platform, device, system version, and region. We do not guarantee that every detector, format, or third-party capability will always remain available.'] },
          { id: 'third-party', title: '9. Third-party services', paragraphs: ['App stores, operating systems, external websites, social platforms, and email are provided by third parties and governed by their own terms. GCSA does not control their availability or data practices.'] },
          { id: 'disclaimer', title: '10. Disclaimers and limitation of liability', paragraphs: ['To the maximum extent permitted by applicable law, WATERMARK is provided “as is” and “as available,” without implied warranties of inspection completeness, merchantability, fitness for a particular purpose, or non-infringement.', 'To the maximum extent permitted by applicable law, GCSA is not liable for indirect, incidental, special, or consequential loss arising from use or inability to use the app, reliance on results, data loss, or third-party services. Rights that cannot legally be excluded remain unaffected.'] },
          { id: 'changes', title: '11. Changes to these Terms', paragraphs: ['We may update these Terms and will show the new effective date on this page. Continued use of an updated app means the user accepts the terms then in effect. A user who does not agree should stop using and uninstall the app.'] },
        ],
        contactTitle: 'Questions about these Terms',
        contactDescription: 'Contact GCSA with questions about licensing, product boundaries, or these Terms.',
        contactAction: 'Email contact@gcsa.org',
      },
      support: {
        eyebrow: 'TECHNICAL SUPPORT',
        title: 'Technical Support',
        summary: 'Find help for using the iOS and Android apps, interpreting results, managing local privacy data, and troubleshooting common problems.',
        dateLabel: 'Last updated',
        date: 'August 1, 2026',
        sections: [
          { id: 'start', title: '1. Quick start', paragraphs: ['WATERMARK does not require an account or sign-in. Open the app, choose media from Photos, the system file picker, or the clipboard, and begin an on-device inspection.'], bullets: ['Choose an image, video, or audio file you have the right to process.', 'Allow the app to plan and run the checks supported on the current device.', 'Read the overall conclusion, then expand the evidence, warnings, skipped checks, and capability limits.', 'Before sharing an image, review Smart Redaction suggestions and export a new PNG copy.'] },
          { id: 'import', title: '2. Media cannot be imported or read', paragraphs: ['Confirm that the file is not damaged, the device has enough free space, and the system picker has granted access for this selection. Readable formats depend on operating-system decoding and current detector support.', 'If a target item does not appear in Photos or Files, first confirm that the corresponding system app can open it, then select it again.'] },
          { id: 'results', title: '3. Understanding results', paragraphs: ['“No supported watermark found” does not prove that no watermark exists. “Suspected” needs human review. “Skipped” or “unsupported” means the format, model, profile, signature material, or runtime condition was unavailable.', 'Review detector status, evidence, warnings, and sampling scope together instead of relying on a single status label as proof of authenticity.'] },
          { id: 'redaction', title: '4. Smart Redaction', paragraphs: ['Smart Redaction suggests faces and sensitive text regions locally. Automatic suggestions can miss or misidentify content, so users should review, move, resize, add, or remove every region before export.', 'Export creates a new PNG without original metadata and does not overwrite the source image. Smart Redaction is not a watermark-removal tool.'] },
          { id: 'history', title: '5. History and local data', paragraphs: ['Inspection reports, thumbnails, managed copies, and redaction projects are stored in the app’s local directory. Users can delete records in the app; clearing app data or uninstalling the app also removes content in the app container.', 'Deleting an in-app record does not delete the original media in Photos or Files.'] },
          { id: 'troubleshooting', title: '6. Troubleshooting', paragraphs: [], bullets: ['Update WATERMARK to the latest version offered by the app store.', 'Confirm that iOS or Android is updated to a supported version.', 'Close and reopen the app, then retry the same media.', 'Confirm that the device has free storage and review the Photos or Files access granted by the system.', 'If one file consistently fails, note its type, size, and the visible error. Do not send a sensitive original by default.'] },
          { id: 'contact', title: '7. Contact technical support', paragraphs: ['When emailing support, include the device model, system version, WATERMARK version, steps to reproduce, and any visible error. Do not attach media, reports, or source images containing personal information unless it is necessary and you choose to do so.', 'WATERMARK requires no test account and has no subscription or in-app-purchase restoration flow.'] },
        ],
        contactTitle: 'Need more help?',
        contactDescription: 'Contact GCSA technical support by email. Do not send unrelated sensitive media.',
        contactAction: 'Email contact@gcsa.org',
      },
    },
  },
}
