import type { Locale, SiteCopy } from '../types/site'

export const languageOptions: Array<{ code: Locale; label: string; short: string }> = [
  { code: 'zh-CN', label: '简体中文', short: 'CN' },
  { code: 'zh-Hant', label: '繁體中文', short: '繁' },
  { code: 'en', label: 'English', short: 'EN' },
]

export const siteCopy: Record<Locale, SiteCopy> = {
  'zh-CN': {
    skipMain: '跳过导航，前往主要内容',
    homeLabel: '返回水印分析首页',
    navLabel: '页面导航',
    openMenu: '打开导航菜单',
    closeMenu: '关闭导航菜单',
    languageLabel: '切换语言',
    switchToLight: '切换到浅色主题',
    switchToDark: '切换到深色主题',
    headerCta: '了解能力',
    nav: [
      { href: '#capabilities', label: '检测能力' },
      { href: '#workflow', label: '检测流程' },
      { href: '#redaction', label: '智能打码' },
      { href: '#privacy', label: '隐私边界' },
    ],
    hero: {
      ecosystem: 'GCSA 生态产品',
      eyebrow: 'IOS & ANDROID MEDIA INSPECTION',
      title: '在手机本地，看懂媒体中的水印信号',
      lead: '在 iPhone 与 Android 设备上检查图片、视频和音频中当前版本支持的内容凭证、水印信号与可疑特征，并把结论、证据和能力限制整理成可复核的报告。',
      primaryAction: '查看检测能力',
      secondaryAction: '了解隐私边界',
      proof: '隐私优先设计 · 媒体原文件和检测数据默认不会上传',
      visualLabel: '水印分析 iOS 与 Android 移动应用预览',
      visualInput: '媒体输入',
      visualScanning: '本地扫描中',
      visualResult: '检测报告',
      visualFound: '已识别凭证',
      visualReview: '1 项需复核',
      visualReady: '报告已生成',
    },
    facts: [
      { value: 'iOS / Android', label: '移动端应用', description: '为 iPhone 与 Android 设备设计' },
      { value: '图片 / 视频 / 音频', label: '多媒体检查', description: '从照片、文件或剪贴板导入' },
      { value: '本地优先', label: '处理边界', description: '检测与打码默认在手机上完成' },
    ],
    capability: {
      eyebrow: 'SUPPORTED INSPECTION',
      title: '把多类信号，放进同一个检查流程',
      description: '每一项结果都区分已检测、疑似、未执行与能力限制，不用单一信号替代完整判断。',
      items: [
        { tag: 'CREDENTIALS', title: '内容凭证检查', description: '检查当前支持的 C2PA / Content Credentials，展示凭证、签名链与验证限制。' },
        { tag: '水印分析', title: '已知水印信号', description: '针对当前版本登记的图片、音频与视频水印规则，给出发现、候选或不支持原因。' },
        { tag: 'METADATA', title: '元数据与文件摘要', description: '读取适用的 EXIF、XMP 与容器信息，并展示 MIME、文件大小和 SHA-256 摘要。' },
        { tag: 'EVIDENCE', title: '可解释检测报告', description: '从总体结论进入检测器版本、证据、警告、未执行原因和可见候选位置。' },
        { tag: 'BOUNDARY', title: '审慎的结果语义', description: '“未发现”只代表当前已执行范围内未识别到支持信号，不被包装成绝对结论。' },
        { tag: 'HISTORY', title: '本地历史记录', description: '在本机回看最近检测结果，并删除报告、缩略图和 App 管理的受管副本。' },
      ],
    },
    flow: {
      eyebrow: 'HOW IT WORKS',
      title: '从媒体导入，到证据可复核',
      description: '流程优先保留原始文件表示；单个检测器不可用时，会明确保留原因。',
      steps: [
        { number: '01', title: '选择媒体', description: '从照片库、“文件”或剪贴板导入用户主动选择的内容。' },
        { number: '02', title: '本地规划检测', description: '识别媒体类型与运行能力，安排适用的凭证、元数据和水印检测器。' },
        { number: '03', title: '汇总证据', description: '把发现、失败、未执行项和能力限制组织为层次清晰的报告。' },
        { number: '04', title: '回看与管理', description: '在设备本地保存历史，并由用户决定何时查看或删除。' },
      ],
    },
    redaction: {
      eyebrow: 'SMART REDACTION',
      title: '分享之前，先把敏感信息留在自己手里',
      description: '智能打码是独立的本地隐私工具。它给出人脸和敏感文字候选，由用户逐项复核、调整或新增区域。',
      points: [
        '人脸、车牌、证件号、银行卡号、姓名与地址等候选区域',
        '支持启用、停用、新增、移动、缩放、删除以及撤销和重做',
        '可选马赛克、纯色、人脸贴图或自定义图片样式',
        '导出不含原图元数据的新 PNG 副本，不覆盖原图',
      ],
      badge: '不是水印移除工具',
      visualLabel: '智能打码编辑预览',
      visualFace: '人脸',
      visualText: '敏感文字',
      visualExport: '导出新副本',
    },
    privacy: {
      eyebrow: 'PRIVACY BY DEFAULT',
      title: '媒体内容留在设备上',
      description: '原文件、缩略图、元数据、检测中间结果、OCR 原文与编辑区域不会被上传到云端处理。',
      points: [
        { title: '用户主动选择', description: '只处理用户从系统入口主动选取或粘贴的媒体，不在后台扫描照片库或监控剪贴板。' },
        { title: '本地保存与删除', description: '检测报告和编辑历史保存在 App 本地目录，并可由用户删除。' },
        { title: '导出由用户决定', description: '打码结果通过系统分享面板选择去向，App 不会自动上传导出的副本。' },
        { title: '有限诊断与分析', description: '崩溃、性能诊断和有限使用分析会发送给 Firebase，但均不附带用户选择的媒体或检测内容。' },
      ],
      note: '水印分析不提供移除水印、破坏内容凭证或规避平台检测的功能。',
    },
    faq: {
      eyebrow: 'CLEAR LIMITS',
      title: '明确能力，也明确边界',
      description: '可信的检测工具不仅要说明发现了什么，也要说明没有覆盖什么。',
      items: [
        { question: '“未发现”是否代表媒体没有水印？', answer: '不是。它只表示当前版本在已经执行的检测范围内没有识别到支持的信号。未知算法、闭源水印、截图、裁剪、转码和压缩都可能影响结果。' },
        { question: '可以证明一张图片真实吗？', answer: '不能。有效的内容凭证可以提供来源和编辑链证据，但任何单一检测结果都不能被描述为对媒体真实性的绝对证明。' },
        { question: '可以识别所有 AI 生成内容吗？', answer: '不能。水印分析检查内容凭证、已知水印和异常信号，不承诺识别所有 AI 生成媒体。' },
        { question: '智能打码会删除水印吗？', answer: '不会。智能打码用于遮挡人脸和敏感内容，不提供水印移除、内容凭证破坏或检测规避能力。' },
      ],
    },
    closing: {
      eyebrow: 'INSPECT WITH CONTEXT',
      title: '让每一次检测，都能回到证据本身',
      description: '水印分析以本地处理和可解释结论为基础，帮助你更审慎地理解媒体中的凭证、水印信号与风险提示。',
      action: '返回顶部',
    },
    ecosystem: {
      eyebrow: 'GCSA 安全生态',
      title: '更多安全产品',
      description: '从链上资产、网络隐私到家庭与金融环境，将安全防护延伸到每一次数字操作。',
      officialWebsite: '前往官网',
      moreTitle: '更多安全产品',
      moreDescription: '探索完整的 GCSA 安全生态，查看更多面向个人、企业与基础设施的安全产品。',
      viewAll: '查看全部产品',
      products: [
        {
          type: '安全加密钱包',
          name: 'GCSA Wallet',
          description: 'GCSA Wallet 为个人与团队提供安全的数字资产管理与链上风险识别体验，帮助用户更安心地查看、接收与转移资产。',
          features: ['实时地址风险扫描', '智能资金来源追踪', 'AI 异常风险告警'],
          href: 'https://wallet.gcsa.org/',
          theme: 'wallet',
        },
        {
          type: '加密网络与隐私保护',
          name: 'GCSA VPN',
          description: 'GCSA VPN 通过加密连接保护日常上网与公共网络使用，降低数据泄露风险，为不同设备提供简单、稳定的安全连接。',
          features: ['加密网络连接', '上网隐私保护', '多设备安全访问'],
          href: 'https://gsafevpn.com/',
          theme: 'vpn',
        },
        {
          type: '家庭与金融移动安全',
          name: 'GCSA Home Guard',
          description: 'GCSA Home Guard 是面向家庭与金融场景的移动安全体检平台，结合安全评分、修复建议与云端威胁情报，及早识别设备漏洞、环境风险与 AI 诈骗威胁。',
          features: ['一键安全体检', '家庭设备与摄像头安全', 'AI 诈骗与钓鱼防护'],
          href: 'https://homeguard.gcsa.org/',
          theme: 'homeGuard',
        },
      ],
    },
    footer: {
      menuLabel: '底栏导航',
      contactUs: '联系我们',
      email: '联系邮箱',
      twitter: '推特',
      telegram: 'Telegram',
      home: '首页',
      products: 'GCSA 生态产品',
      media: 'GCSA 媒体',
      updates: 'GCSA 动态',
      join: '加入联盟',
      about: '关于联盟',
      privacy: '隐私政策',
      terms: '使用条款',
      support: '技术支持',
      copyright: '© Global Cybersecurity Alliance Limited. 保留所有权利。',
    },
  },
  'zh-Hant': {
    skipMain: '跳過導覽，前往主要內容',
    homeLabel: '返回水印分析首頁',
    navLabel: '頁面導覽',
    openMenu: '開啟導覽選單',
    closeMenu: '關閉導覽選單',
    languageLabel: '切換語言',
    switchToLight: '切換至淺色主題',
    switchToDark: '切換至深色主題',
    headerCta: '了解能力',
    nav: [
      { href: '#capabilities', label: '檢測能力' },
      { href: '#workflow', label: '檢測流程' },
      { href: '#redaction', label: '智能打碼' },
      { href: '#privacy', label: '私隱邊界' },
    ],
    hero: {
      ecosystem: 'GCSA 生態產品',
      eyebrow: 'IOS & ANDROID MEDIA INSPECTION',
      title: '在手機本地，看懂媒體中的浮水印訊號',
      lead: '在 iPhone 與 Android 裝置上檢查圖片、影片和音訊中目前版本支援的內容憑證、浮水印訊號與可疑特徵，並把結論、證據和能力限制整理成可覆核的報告。',
      primaryAction: '查看檢測能力',
      secondaryAction: '了解私隱邊界',
      proof: '私隱優先設計 · 媒體原檔和檢測資料預設不會上傳',
      visualLabel: '水印分析 iOS 與 Android 移動應用預覽',
      visualInput: '媒體輸入',
      visualScanning: '本地掃描中',
      visualResult: '檢測報告',
      visualFound: '已識別憑證',
      visualReview: '1 項需覆核',
      visualReady: '報告已產生',
    },
    facts: [
      { value: 'iOS / Android', label: '移動端應用', description: '為 iPhone 與 Android 裝置設計' },
      { value: '圖片 / 影片 / 音訊', label: '多媒體檢查', description: '從相片、檔案或剪貼簿匯入' },
      { value: '本地優先', label: '處理邊界', description: '檢測與打碼預設在手機完成' },
    ],
    capability: {
      eyebrow: 'SUPPORTED INSPECTION',
      title: '把多類訊號，放進同一個檢查流程',
      description: '每一項結果都區分已檢測、疑似、未執行與能力限制，不以單一訊號取代完整判斷。',
      items: [
        { tag: 'CREDENTIALS', title: '內容憑證檢查', description: '檢查目前支援的 C2PA / Content Credentials，展示憑證、簽章鏈與驗證限制。' },
        { tag: '水印分析', title: '已知浮水印訊號', description: '針對目前版本登記的圖片、音訊與影片浮水印規則，給出發現、候選或不支援原因。' },
        { tag: 'METADATA', title: '中繼資料與檔案摘要', description: '讀取適用的 EXIF、XMP 與容器資訊，並展示 MIME、檔案大小和 SHA-256 摘要。' },
        { tag: 'EVIDENCE', title: '可解釋檢測報告', description: '從整體結論進入檢測器版本、證據、警告、未執行原因和可見候選位置。' },
        { tag: 'BOUNDARY', title: '審慎的結果語義', description: '「未發現」只代表目前已執行範圍內未識別支援訊號，不包裝成絕對結論。' },
        { tag: 'HISTORY', title: '本地歷史記錄', description: '在本機回看最近檢測結果，並刪除報告、縮圖和 App 管理的副本。' },
      ],
    },
    flow: {
      eyebrow: 'HOW IT WORKS',
      title: '從媒體匯入，到證據可覆核',
      description: '流程優先保留原始檔案表示；個別檢測器不可用時，會清楚保留原因。',
      steps: [
        { number: '01', title: '選擇媒體', description: '從相片庫、「檔案」或剪貼簿匯入使用者主動選擇的內容。' },
        { number: '02', title: '本地規劃檢測', description: '識別媒體類型與執行能力，安排適用的憑證、中繼資料和浮水印檢測器。' },
        { number: '03', title: '彙整證據', description: '把發現、失敗、未執行項和能力限制組織成層次清晰的報告。' },
        { number: '04', title: '回看與管理', description: '在裝置本地保存歷史，並由使用者決定何時查看或刪除。' },
      ],
    },
    redaction: {
      eyebrow: 'SMART REDACTION',
      title: '分享之前，先把敏感資料留在自己手裡',
      description: '智能打碼是獨立的本地私隱工具。它提供人臉和敏感文字候選，由使用者逐項覆核、調整或新增區域。',
      points: [
        '人臉、車牌、證件號、銀行卡號、姓名與地址等候選區域',
        '支援啟用、停用、新增、移動、縮放、刪除以及復原和重做',
        '可選馬賽克、純色、人臉貼圖或自訂圖片樣式',
        '匯出不含原圖中繼資料的新 PNG 副本，不覆蓋原圖',
      ],
      badge: '不是浮水印移除工具',
      visualLabel: '智能打碼編輯預覽',
      visualFace: '人臉',
      visualText: '敏感文字',
      visualExport: '匯出新副本',
    },
    privacy: {
      eyebrow: 'PRIVACY BY DEFAULT',
      title: '媒體內容留在裝置上',
      description: '原檔、縮圖、中繼資料、檢測中間結果、OCR 原文與編輯區域不會上傳到雲端處理。',
      points: [
        { title: '使用者主動選擇', description: '只處理使用者從系統入口主動選取或貼上的媒體，不在背景掃描相片庫或監控剪貼簿。' },
        { title: '本地保存與刪除', description: '檢測報告和編輯歷史保存在 App 本地目錄，並可由使用者刪除。' },
        { title: '匯出去向由你決定', description: '打碼結果透過系統分享面板選擇去向，App 不會自動上傳匯出的副本。' },
        { title: '有限診斷與分析', description: '崩潰、效能診斷和有限使用分析會傳送給 Firebase，但均不附帶用戶選擇的媒體或檢測內容。' },
      ],
      note: '水印分析不提供移除浮水印、破壞內容憑證或規避平台檢測的功能。',
    },
    faq: {
      eyebrow: 'CLEAR LIMITS',
      title: '明確能力，也明確邊界',
      description: '可信的檢測工具不只要說明發現了甚麼，也要說明沒有覆蓋甚麼。',
      items: [
        { question: '「未發現」是否代表媒體沒有浮水印？', answer: '不是。它只表示目前版本在已執行的檢測範圍內沒有識別支援訊號。未知演算法、封閉水印、截圖、裁剪、轉碼和壓縮都可能影響結果。' },
        { question: '可以證明一張圖片真實嗎？', answer: '不能。有效的內容憑證可以提供來源和編輯鏈證據，但任何單一檢測結果都不能視為對媒體真實性的絕對證明。' },
        { question: '可以識別所有 AI 生成內容嗎？', answer: '不能。水印分析檢查內容憑證、已知浮水印和異常訊號，不承諾識別所有 AI 生成媒體。' },
        { question: '智能打碼會刪除浮水印嗎？', answer: '不會。智能打碼用於遮擋人臉和敏感內容，不提供浮水印移除、內容憑證破壞或檢測規避能力。' },
      ],
    },
    closing: {
      eyebrow: 'INSPECT WITH CONTEXT',
      title: '讓每一次檢測，都能回到證據本身',
      description: '水印分析以本地處理和可解釋結論為基礎，幫助你更審慎地理解媒體中的憑證、浮水印訊號與風險提示。',
      action: '返回頂部',
    },
    ecosystem: {
      eyebrow: 'GCSA 安全生態',
      title: '更多安全產品',
      description: '從鏈上資產、網路私隱到家庭與金融環境，將安全防護延伸到每一次數碼操作。',
      officialWebsite: '前往官網',
      moreTitle: '更多安全產品',
      moreDescription: '探索完整的 GCSA 安全生態，查看更多面向個人、企業與基礎設施的安全產品。',
      viewAll: '查看全部產品',
      products: [
        {
          type: '安全加密錢包',
          name: 'GCSA Wallet',
          description: 'GCSA Wallet 為個人與團隊提供安全的數碼資產管理與鏈上風險識別體驗，協助用戶更安心地查看、接收與轉移資產。',
          features: ['即時地址風險掃描', '智能資金來源追蹤', 'AI 異常風險告警'],
          href: 'https://wallet.gcsa.org/',
          theme: 'wallet',
        },
        {
          type: '加密網路與私隱保護',
          name: 'GCSA VPN',
          description: 'GCSA VPN 透過加密連線保護日常上網與公共網路使用，降低資料外洩風險，為不同裝置提供簡單、穩定的安全連線。',
          features: ['加密網路連線', '上網私隱保護', '多裝置安全存取'],
          href: 'https://gsafevpn.com/',
          theme: 'vpn',
        },
        {
          type: '家庭與金融移動安全',
          name: 'GCSA Home Guard',
          description: 'GCSA Home Guard 是面向家庭與金融場景的移動安全體檢平台，結合安全評分、修復建議與雲端威脅情報，及早識別裝置漏洞、環境風險與 AI 詐騙威脅。',
          features: ['一鍵安全體檢', '家庭設備與攝像頭安全', 'AI 詐騙與釣魚防護'],
          href: 'https://homeguard.gcsa.org/',
          theme: 'homeGuard',
        },
      ],
    },
    footer: {
      menuLabel: '頁尾導覽',
      contactUs: '聯繫我們',
      email: '聯繫郵箱',
      twitter: '推特',
      telegram: 'Telegram',
      home: '首頁',
      products: 'GCSA 生態產品',
      media: 'GCSA 媒體',
      updates: 'GCSA 動態',
      join: '加入聯盟',
      about: '關於聯盟',
      privacy: '隱私政策',
      terms: '使用條款',
      support: '技術支持',
      copyright: '© Global Cybersecurity Alliance Limited. 保留所有權利。',
    },
  },
  en: {
    skipMain: 'Skip navigation and go to main content',
    homeLabel: 'Back to the WATERMARK home page',
    navLabel: 'Page navigation',
    openMenu: 'Open navigation menu',
    closeMenu: 'Close navigation menu',
    languageLabel: 'Switch language',
    switchToLight: 'Switch to light theme',
    switchToDark: 'Switch to dark theme',
    headerCta: 'Explore',
    nav: [
      { href: '#capabilities', label: 'Inspection' },
      { href: '#workflow', label: 'Workflow' },
      { href: '#redaction', label: 'Redaction' },
      { href: '#privacy', label: 'Privacy' },
    ],
    hero: {
      ecosystem: 'A GCSA ecosystem product',
      eyebrow: 'IOS & ANDROID MEDIA INSPECTION',
      title: 'Understand watermark signals right on your phone',
      lead: 'Inspect supported content credentials, watermark signals, and suspicious characteristics in images, video, and audio on iPhone and Android—then review the conclusion, evidence, and capability limits in one report.',
      primaryAction: 'Explore inspection',
      secondaryAction: 'View privacy boundary',
      proof: 'Privacy-first by design · Original media and inspection data stay local by default',
      visualLabel: 'WATERMARK mobile app preview for iOS and Android',
      visualInput: 'Media input',
      visualScanning: 'Scanning locally',
      visualResult: 'Inspection report',
      visualFound: 'Credential found',
      visualReview: '1 item to review',
      visualReady: 'Report ready',
    },
    facts: [
      { value: 'iOS / Android', label: 'Mobile apps', description: 'Designed for iPhone and Android devices' },
      { value: 'Image / Video / Audio', label: 'Media coverage', description: 'Import from Photos, Files, or clipboard' },
      { value: 'Local first', label: 'Processing boundary', description: 'Inspection and redaction run on your phone by default' },
    ],
    capability: {
      eyebrow: 'SUPPORTED INSPECTION',
      title: 'Multiple signals, one careful workflow',
      description: 'Each result distinguishes findings, suspected signals, skipped checks, and capability limits instead of turning one signal into a blanket claim.',
      items: [
        { tag: 'CREDENTIALS', title: 'Content credentials', description: 'Inspect supported C2PA / Content Credentials and review credentials, signature chains, and verification limits.' },
        { tag: 'WATERMARK', title: 'Known watermark signals', description: 'Run registered image, audio, and video rules and show a finding, candidate, or reason a check is unsupported.' },
        { tag: 'METADATA', title: 'Metadata and file summary', description: 'Read applicable EXIF, XMP, and container data alongside MIME type, file size, and a SHA-256 digest.' },
        { tag: 'EVIDENCE', title: 'Explainable reports', description: 'Move from a plain-language conclusion into detector versions, evidence, warnings, skipped checks, and visible candidates.' },
        { tag: 'BOUNDARY', title: 'Careful result language', description: '“Not found” means no supported signal was identified within completed checks—not that no watermark exists.' },
        { tag: 'HISTORY', title: 'Local history', description: 'Review recent results on device and delete reports, thumbnails, and copies managed by the app.' },
      ],
    },
    flow: {
      eyebrow: 'HOW IT WORKS',
      title: 'From selected media to reviewable evidence',
      description: 'The workflow prefers the original file representation and preserves a clear reason whenever an individual detector cannot run.',
      steps: [
        { number: '01', title: 'Choose media', description: 'Import content you explicitly select from Photos, Files, or the clipboard.' },
        { number: '02', title: 'Plan local checks', description: 'Identify the media type and available runtime capabilities, then schedule applicable checks.' },
        { number: '03', title: 'Assemble evidence', description: 'Organize findings, failures, skipped checks, and capability limits into a structured report.' },
        { number: '04', title: 'Review and manage', description: 'Keep history on device and decide when to revisit or remove it.' },
      ],
    },
    redaction: {
      eyebrow: 'SMART REDACTION',
      title: 'Protect sensitive details before you share',
      description: 'Smart Redaction is a separate on-device privacy tool. It suggests faces and sensitive text regions for you to review, adjust, or add manually.',
      points: [
        'Candidate regions for faces, plates, IDs, card numbers, names, and addresses',
        'Enable, disable, add, move, resize, delete, undo, and redo',
        'Mosaic, solid color, face sticker, or a custom image style',
        'Export a new PNG without original metadata; the source image stays untouched',
      ],
      badge: 'Not a watermark removal tool',
      visualLabel: 'Smart redaction editor preview',
      visualFace: 'Face',
      visualText: 'Sensitive text',
      visualExport: 'Export new copy',
    },
    privacy: {
      eyebrow: 'PRIVACY BY DEFAULT',
      title: 'Media stays on your device',
      description: 'Original files, thumbnails, metadata, detector intermediates, OCR text, and edit regions are not sent to the cloud for processing.',
      points: [
        { title: 'You choose the input', description: 'The app processes only media you select or paste. It does not silently scan the photo library or monitor the clipboard.' },
        { title: 'Local storage and deletion', description: 'Inspection reports and editing history live in the app’s local directory and can be deleted by you.' },
        { title: 'You choose the destination', description: 'The system share sheet controls where an exported copy goes; the app does not upload it automatically.' },
        { title: 'Limited diagnostics and analytics', description: 'Crash and performance diagnostics and limited usage analytics are sent to Firebase without selected media or inspection content.' },
      ],
      note: 'WATERMARK does not remove watermarks, damage content credentials, or help evade platform detection.',
    },
    faq: {
      eyebrow: 'CLEAR LIMITS',
      title: 'Clear about capabilities—and limits',
      description: 'A trustworthy inspection tool should explain both what it found and what it did not cover.',
      items: [
        { question: 'Does “not found” prove there is no watermark?', answer: 'No. It only means the current version did not identify a supported signal within completed checks. Unknown algorithms, closed systems, screenshots, cropping, transcoding, and compression can all affect results.' },
        { question: 'Can the app prove an image is authentic?', answer: 'No. A valid content credential can provide provenance and edit-chain evidence, but no single result is absolute proof of media authenticity.' },
        { question: 'Can it identify every piece of AI-generated media?', answer: 'No. WATERMARK inspects content credentials, known watermarks, and anomalous signals; it does not claim to recognize all AI-generated media.' },
        { question: 'Does Smart Redaction remove watermarks?', answer: 'No. Smart Redaction masks faces and sensitive content. It does not remove watermarks, damage content credentials, or evade detection.' },
      ],
    },
    closing: {
      eyebrow: 'INSPECT WITH CONTEXT',
      title: 'Bring every result back to the evidence',
      description: 'WATERMARK combines local processing with explainable conclusions so you can evaluate credentials, watermark signals, and risk indicators with the right context.',
      action: 'Back to top',
    },
    ecosystem: {
      eyebrow: 'GCSA Security Ecosystem',
      title: 'More security products',
      description: 'Extend protection from on-chain assets and online privacy to every digital interaction at home and across financial environments.',
      officialWebsite: 'Official website',
      moreTitle: 'More security products',
      moreDescription: 'Explore the complete GCSA security ecosystem and discover more products for individuals, businesses, and infrastructure.',
      viewAll: 'View all products',
      products: [
        {
          type: 'Secure crypto wallet',
          name: 'GCSA Wallet',
          description: 'GCSA Wallet gives individuals and teams a secure digital-asset management and on-chain risk experience for viewing, receiving, and transferring assets with greater confidence.',
          features: ['Real-time address risk screening', 'Intelligent source-of-funds tracing', 'AI-powered anomaly alerts'],
          href: 'https://wallet.gcsa.org/',
          theme: 'wallet',
        },
        {
          type: 'Encrypted network & privacy',
          name: 'GCSA VPN',
          description: 'GCSA VPN protects everyday browsing and public-network use with encrypted connections, helping reduce data exposure across devices through simple, reliable secure access.',
          features: ['Encrypted connections', 'Online privacy protection', 'Secure multi-device access'],
          href: 'https://gsafevpn.com/',
          theme: 'vpn',
        },
        {
          type: 'Home & financial mobile security',
          name: 'GCSA Home Guard',
          description: 'GCSA Home Guard is a mobile security checkup platform for home and financial scenarios, combining security scores, remediation guidance, and cloud threat intelligence to surface device vulnerabilities, environmental risks, and AI-driven scams early.',
          features: ['One-tap security checkup', 'Home device & camera security', 'AI scam & phishing protection'],
          href: 'https://homeguard.gcsa.org/',
          theme: 'homeGuard',
        },
      ],
    },
    footer: {
      menuLabel: 'Footer navigation',
      contactUs: 'Contact Us',
      email: 'Email',
      twitter: 'Twitter',
      telegram: 'Telegram',
      home: 'Home',
      products: 'GCSA Ecosystem Products',
      media: 'GCSA Media',
      updates: 'GCSA Updates',
      join: 'Join the Alliance',
      about: 'About Alliance',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      support: 'Technical Support',
      copyright: '© Global Cybersecurity Alliance Limited. All rights reserved.',
    },
  },
}
